### ISSUE TITLE
Standard 404 rule causes infinite redirect when running static Hugo site with dev command

### ISSUE THREAD

**Issue by LandGod** [netlify/cli#1595] opened 2020-11-25 20:51 UTC
**Describe the bug**
The following has been present, unchanged, in our `_redirects` file on our live site without any issues for months if not years:
```
/* /404.html 404
```
However, it seems that this redirect command causes the website served by `netlify dev` to enter an infinite redirect loop when trying to navigate to any page, including `/`. This renders the entire site inaccessible. Removing this line from `_redirects` causes the site to work as normal (although 404s then simply redirect to the home page instead of displaying 404.html). 

My reading of the docs suggests that this should be a valid rule and that this would be expected behavior only if `!` was used, which it is not in this case. 

**To Reproduce**
Unfortunately I cannot share our GitHub repository as it is private, however this is the full text of our `_redirects` file:
[_redirects.txt](https://github.com/netlify/cli/files/5599195/_redirects.txt) (`.txt` added so Github would allow the upload)
The issue happens when the last line is un-commented. 

You can see these rules in action on our live site at [jaquishbiomedical.com](https://www.jaquishbiomedical.com/)

**Configuration**

- If possible, please copy/paste below your `netlify.toml`:
<details>
<summary>Full netlify.toml</summary>

```
# Default build command.
[build]
publish = "public"
command = "hugo --gc --minify --baseURL $URL --environment production"
HUGO_VERSION = "0.78.2"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"


##############################################################################
# Master branch context: all deploys from the Master branch set in your site's
# deploy contexts will inherit these settings.
##############################################################################

[context.master]
command = "hugo --gc --minify --enableGitInfo --baseURL $URL --environment production"

[context.master.environment]
HUGO_ENV = "production"
HUGO_VERSION = "0.78.2"
HUGO_ENABLEGITINFO = "true"


##############################################################################
# Staging branch context: all deploys from the staging branch set in your site's
# deploy contexts will inherit these settings.
##############################################################################

[context.staging]
command = "hugo --gc --minify --enableGitInfo --baseURL $URL --environment development"

[context.staging.environment]
HUGO_ENV = "development"
HUGO_VERSION = "0.78.2"
HUGO_ENABLEGITINFO = "true"

##############################################################################
# Deploy Preview context: all deploys generated from a pull/merge request will
# inherit these settings.
##############################################################################

[context.deploy-preview]
command = "hugo --gc --buildFuture --baseURL $DEPLOY_PRIME_URL --environment development"

[context.deploy-preview.environment]
HUGO_ENV = "development"
HUGO_VERSION = "0.78.2"
HUGO_ENABLEGITINFO = "true"

##############################################################################
# Devstore Deploy Context: 
# 
##############################################################################

[context.task1314c]
command = "hugo --gc --minify --enableGitInfo --baseURL $URL --environment devstore --config config.toml,devstoreconfig.toml"

[context.task1314c.environment]
HUGO_ENV = "devstore"
HUGO_VERSION = "0.78.2"
HUGO_ENABLEGITINFO = "true"


##############################################################################
# Branch Deploy context: all deploys that are not from a pull/merge request or
# from the Production branch will inherit these settings.
##############################################################################

[context.branch-deploy]
command = "hugo --gc --baseURL $DEPLOY_PRIME_URL --environment development"

[context.branch-deploy.environment]
HUGO_ENV = "development"
HUGO_VERSION = "0.78.2"
HUGO_ENABLEGITINFO = "true"


##############################################################################
# devsite.jaquishbiomedical.com just a site to always have the devstore products running
##############################################################################

[context.devstore]
command = "hugo --gc --minify --enableGitInfo --baseURL $URL --config config.toml,devstoreconfig.toml --environment devstore"

[context.devstore.environment]
HUGO_ENV = "development"
HUGO_VERSION = "0.77.0"
HUGO_ENABLEGITINFO = "true"

##############################################################################
# Develop site context: must manually set branch
##############################################################################

[context.task1607a-save-fb-tracking-data-for-shopify]
command = "hugo --gc --minify --enableGitInfo --baseURL $URL --environment development"

[context.task1607a-save-fb-tracking-data-for-shopify.environment]
HUGO_ENV = "development"
HUGO_VERSION = "0.78.2"
HUGO_ENABLEGITINFO = "true"

##############################################################################
# Plugins
##############################################################################
#[[plugins]]
#package = "netlify-plugin-cypress"
#    [plugins.inputs]
#    record = true

##############################################################################
# Headers
# For info about Netlify/TOML header formatting see: https://docs.netlify.com/routing/headers/#syntax-for-the-headers-file
##############################################################################
[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Strict-Transport-Security = '''
    max-age=63072000,
    includeSubDomains, 
    preload'''
  
# Proxy Caching
# The default Netlify cache-control header, are `max-age=0, must-revalidate, public` which means all content should be cached but also re-validated.
# `s-max-age` Takes precedence over `max-age` or the `Expires` header, but it only applies to shared caches (e.g., proxies) and is ignored by a private cache. This means we’re using custom headers on Netlify to tell Cloudflare (our CDN) how long to cache assets. We’ll then control how long browsers cache using CDN settings.
# 604800 seconds translates to 7 days, so during normal operation Cloudflare will cache images, CSS and JavaScript files for 7 days.
# Even if Cloudflare has cached our .css or .js we are using adding a hash to the filenames which causes any chance to be cache busting. Hugo has a cache-busting hash baked in called fingerprinting.  Old versions and new versions will be fetched and cached separately due to this new filename with a hash. This makes it safe to aggressively cache across the CDN and in browsers.
# For more info: https://developers.google.com/web/fundamentals/performance/optimizing-content-efficiency/http-caching#defining_optimal_cache-control_policy 

# ******** Non-hashed static assets ********
# These we're ok caching for 7 days on a local machine and 7 days on Edge. (see above)
[[headers]]
  for = "/img-gen/*"
  [headers.values]
    cache-control = '''
    public, 
    s-max-age=604800, 
    max-age=604800'''

[[headers]]
  for = "/images*"
  [headers.values]
    cache-control = '''
    public, 
    s-max-age=604800, 
    max-age=604800'''

[[headers]]
  for = "/fonts/*"
  [headers.values]
    cache-control = '''
    public, 
    s-max-age=604800, 
    max-age=604800'''

[[headers]]
  for = "/favicon/*"
  [headers.values]
    cache-control = '''
    public, 
    s-max-age=604800, 
    max-age=604800'''

# ******** Hashed assets ********
# These we're ok to cache for 1 year on a local machine and 1 year on Edge (see above)

[[headers]]
  for = "/*.css"
  [headers.values]
    cache-control = '''
    public, 
    s-max-age=31536000, 
    max-age=31536000'''
  
[[headers]]
  for = "/*.js"
  [headers.values]
    cache-Control = '''
    public, 
    s-max-age=31536000, 
    max-age=31536000'''
```

</details>

```
System:
    OS: Windows 10 10.0.18363
    CPU: (8) x64 Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz
    Memory: 7.40 GB / 15.96 GB
  Binaries:
    Node: 12.13.0 - C:\Program Files\nodejs\node.EXE
    npm: 6.14.8 - C:\Program Files\nodejs\npm.CMD
```

**Expected behavior**
I expect for the local version of the website served by `netlify dev` to be accessible and useable just like it is when the redirect rule is removed.

**CLI Output**
n/a (Site launches successfully) 

**Additional context**
The error causes the only thing visible when trying to visit the site to be the error page showing "too many redirects" error on both Chrome and Firefox.

**Comment by rybrad** [comment] 2021-03-18 03:01
Any word on a fix for this? We use custom 404 pages via redirects for all our sites so this make netlify dev untenable to use currently. Also thanks for posting this @LandGod, I was having a hard time figuring out what was causing this issue.

**Comment by erezrokah** [comment] 2021-03-18 10:11
Hi @rybrad, we have an experimental flag that might help.
Can you try running `ntl dev --edgeHandlers`? That will switch the CLI to use a redirect engine that is much closer to the one we have in production instead of emulating redirects via JavaScript.

**Comment by LandGod** [comment] 2021-03-18 18:19
@erezrokah just tried this and while the home page of my site loads up, clicking any link or trying to manually navigate to any other page it fails.

In the Chrome console I'm seeing `504 (Gateway Timeout)`

And on the page itself all I get is: `Failed to connect to host: Timeout while establishing connection`

No output from the console that I ran `netlify dev --edgeHandlers` in other than the standard server started successfully message and this: `✔ Done processing request remaps, header rules and Edge Handlers`

**Comment by rybrad** [comment] 2021-03-18 20:53
@erezrokah Homepage loads fine, all other pages 404 when I keep the 404 redirect in `_redirects`. When I remove the 404 redirect and try with the` --edgeHandlers` flag it gives me `Failed to connect to host: Timeout while establishing connection`

**Comment by erezrokah** [comment] 2021-04-07 15:58
Sorry for the delay to respond.
Can anyone post a reproduction for this issue? I tried on https://github.com/erezrokah/netlify-build-reproductions/blob/cli/issue_1595/public/_redirects and `netlify dev` works fine for me.

Probably my example is a bit too simple to surface the bug.

**Comment by rybrad** [comment] 2021-04-07 16:27
@erezrokah I downloaded your repo and it did indeed work fine. I tried with an Eleventy site we have and that also worked fine. The original site I tried it on was using Hugo which also is the case for the site @LandGod posted about. I'll see if I can get a minimal Hugo setup and repro.

**Comment by rybrad** [comment] 2021-04-08 16:13
I have a repo that can reproduce the issue in Hugo now: https://github.com/rybrad/netlify-hugo-redirect

With Hugo installed, running `ntl dev` should cause the "page is not redirecting properly/too many redirects" issue. If you comment out the 404 redirect in https://github.com/rybrad/netlify-hugo-redirect/blob/master/site/static/_redirects and refresh, the page will load correctly.

With that being said, I have a couple other observations that may or may not be useful. The issue did not seem to be reproducible when using the default publish directory within Hugo. Also, when changing the `publish` directory in `netlify.toml` to **test** instead of **site/test/** it also seemed to bypass the issue. Not sure how much of that is just a red herring, but figured I would mention it anyway.

**Comment by erezrokah** [comment] 2021-04-22 14:08
Hi @rybrad and sorry for the delay. You' reproduction repo helped a lot.
I wrote a detailed explanation on the cause for the bug here https://github.com/netlify/cli/pull/2195#issue-621121838

**Closed** 2021-04-22 14:56 UTC
Labels: area: command: dev, area: redirects, type: bug
