### ISSUE TITLE
Local environment variables not loaded in CLI 2.38.0+

### ISSUE THREAD

**Issue by cbetta** [netlify/cli#747] opened 2020-03-13 17:56 UTC
**- Do you want to request a _feature_ or report a _bug_?**

A bug

**- What is the current behavior?**

Environment variables in a local `.env` file should be loaded.

**- If the current behavior is a bug, please provide the steps to reproduce.**

Although the CLI detect the `.env` file and prints out all the variables being overriden, none actually are. This behaviour works fine in version 2.37.0 and before. 

**- What is the expected behavior?**

It should load the local `.env` file

**- Local Environment Information**

```
────────────────────┐
 Environment Info   │
────────────────────┘

  System:
    OS: macOS Mojave 10.14.6
    CPU: (12) x64 Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz
  Binaries:
    Node: 13.8.0 - ~/.nvm/versions/node/v13.8.0/bin/node
    Yarn: 1.22.4 - ~/code/box/developer.box.com-framework/node_modules/.bin/yarn
    npm: 6.13.6 - ~/.nvm/versions/node/v13.8.0/bin/npm
  Browsers:
    Chrome: 82.0.4083.0
    Firefox: 72.0.2
    Safari: 13.0.5
  npmGlobalPackages:
    netlify: 3.0.0
```

```
netlify-cli/2.38.0 darwin-x64 node-v13.8.0
```

**Comment by RaeesBhatti** [comment] 2020-03-13 18:08
Thank you for reporting this @cbetta. The issue has been identified and a fix will be released soon https://github.com/netlify/cli/pull/748

**Comment by RaeesBhatti** [comment] 2020-03-13 18:36
A fix for this has been released in `netlify-cli@2.39.0`

**Comment by DarthOstrich** [comment] 2020-03-24 00:12
This is still broken. Do you want me to open up a new issue?

**Comment by RaeesBhatti** [comment] 2020-03-24 00:13
@DarthOstrich Can you please explain the issue you're facing!

**Comment by DarthOstrich** [comment] 2020-03-24 00:18
Hi! When I use CLI v 2.37 my env vars from my local file show up in my react app. When I upgrade past that version (including 2.40) my env variables are the ones in the Netlify dashboard. They are not overwritten by my local file

**Comment by RaeesBhatti** [comment] 2020-03-24 00:21
Is the `.env` file in your project root directory or in your functions directory? The latest Netlify CLI only supports `.env` files in project root directory. We had added support for per-function `.env` files but it was removed recently because you can't set per-function env vars in production.

**Comment by DarthOstrich** [comment] 2020-03-24 00:24
Root directory.

**Comment by RaeesBhatti** [comment] 2020-03-24 00:29
Interesting. I tried this locally and it seems to be working fine. Can you please share a minimal reproducible example of this? Maybe create a repo or share the code here!

**Comment by DarthOstrich** [comment] 2020-03-24 00:53
Curious. I'll throw something together and let you know.

**Comment by DarthOstrich** [comment] 2020-03-24 17:14
Hi @RaeesBhatti . Please see this repo:
https://github.com/DarthOstrich/netlify-test

Running it with CLI version 2.37, the page renders "ImALocalVar", when I upgrade the CLI to 2.40, it renders "ImANetlifyVar"

**Comment by RaeesBhatti** [comment] 2020-03-24 20:04
Thank you for reporting this @DarthOstrich . This is definitely a problem. Most likely a quirk with NodeJS, we're setting the env variables but the changes are not being realized because they're accessed shortly after.
Fixed here: https://github.com/netlify/cli/pull/764

**Comment by DarthOstrich** [comment] 2020-03-24 20:12
Sweet, thanks for getting to this so fast! I spent like 4 hours trying to debug thinking I was doing something wrong haha

**Closed** 2020-03-25 11:31 UTC
