### ISSUE TITLE
Port CLI docs site to new static site tool

### ISSUE THREAD

**Issue by DavidWells** [netlify/cli#304] opened 2019-04-24 23:51 UTC
Future enhancement for cli.netlify.com

`x0` is cool but won't scale to fit the needs of the ref site. So we'll need to put the site into more robust static site tool.

Something like gatsby / react static / phenomic would probably be a better fit.

Stretch goal: Use netlify marketing component library 🚀

**Comment by danez** [comment] 2023-05-05 16:14
Duplicate of #5516

**Closed by danez** 2023-05-05 16:14 UTC
Labels: low-priority, type: chore, area: docs
