### ISSUE TITLE
Mistyped command recognition cause silent exit

### ISSUE THREAD

**Issue by coelmay** [netlify/cli#2873] opened 2021-07-07 22:12 UTC
**Describe the bug**

Netlify CLI very handily recognises that commands are incorrect and offers a command that is correct. This is good 😄  But it doesn't always work out great.

**To Reproduce**

1. Run `ntl deve`
2. Netlify CLI says
    ```
     ›   Warning: deve is not a netlify command.
    Did you mean dev? [y/n]:
    ```
3. Respond with `y`
4. You project starts up, then `netlify-cli` silently exits

**Configuration**

```bash
  System:
    OS: macOS 11.4
    CPU: (12) x64 Intel(R) Core(TM) i5-10600 CPU @ 3.30GHz
    Memory: 2.04 GB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.17.1 - /usr/local/opt/node@14/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.13 - /usr/local/opt/node@14/bin/npm
  npmGlobalPackages:
    netlify-cli: 4.1.12
```
**Note:** This also happened using `netlify-cli/4.0.3`

**Expected behavior**

When running `ntl dev` this behaviour is not observed, it runs correctly. Expectations would have that if the command is wrong Netlify CLI would exit, or if the offer of a **correct** command is accepted that it works as is typing the *proper* command.

**CLI Output**

Using the basic *Netlify Explorers Nuxt Mission* as an example this happens

```
$ ntl deve
 ›   Warning: deve is not a netlify command.
Did you mean dev? [y/n]: y
◈ Netlify Dev ◈
◈ Ignored general context env var: LANG (defined in process)
◈ Injected .env file env var: PUBLISH_DIR
◈ Injected .env file env var: THRESHOLDS
◈ Starting Netlify Dev with nuxt

> nuxt-mission@1.0.0 dev /Users/coel/Documents/GitHub/nuxt-mission
> nuxt

ℹ Listening on: http://localhost:3000/
ℹ Preparing project for development
ℹ Initial build may take a while
ℹ Discovered Components: .nuxt/components/readme.md
✔ Builder initialized

   ┌─────────────────────────────────────────────────┐
   │                                                 │
   │   ◈ Server now ready on http://localhost:8888   │
   │                                                 │
   └─────────────────────────────────────────────────┘

$ 
```
Using the basic *Netlify Explorers Next Mission* as an example this happens
```
$ ntl deve
 ›   Warning: deve is not a netlify command.
Did you mean dev? [y/n]: y
◈ Netlify Dev ◈
◈ Ignored general context env var: LANG (defined in process)
◈ Starting Netlify Dev with create-react-app
yarn run v1.22.10
$ react-scripts start
ℹ ｢wds｣: Project is running at http://192.168.0.137/
ℹ ｢wds｣: webpack output is served from
ℹ ｢wds｣: Content not from webpack is served from /Users/coel/projects/netlify-react-bare/public
ℹ ｢wds｣: 404s will fallback to /
Starting the development server...

Compiled successfully!

You can now view netlify-react-bare in the browser.

  Local:            http://localhost:3000
  On Your Network:  http://192.168.0.137:3000

Note that the development build is not optimized.
To create a production build, use yarn build.


   ┌─────────────────────────────────────────────────┐
   │                                                 │
   │   ◈ Server now ready on http://localhost:8888   │
   │                                                 │
   └─────────────────────────────────────────────────┘

$ 
```

In both cases, the moment the browser loads the page initially it seems to quit.

**Additional context**

I could just learn to type commands better I guess, then I wouldn't have an issue 🤣

**Comment by coelmay** [comment] 2021-07-08 07:24
As an extra note I have found that when `netlify dev` exits in this fashion, the app (e.g. React) is still available on port 3000 as the node instance running it is not terminated.

*(Took me a while to figure out what I continually received a message saying something what already running on port 3000.)*

**Comment by erezrokah** [comment] 2022-02-22 08:59
I couldn't reproduce this so closing as fixed upstream.
If this still happens please comment and I'll re-open

**Closed by erezrokah** 2022-02-22 08:59 UTC
Labels: good first issue, type: bug, area: dx, area: command: dev
