### ISSUE TITLE
Next.js dev environment variables overwritten with production values by netlify dev

### ISSUE THREAD

**Issue by ercgrat** [netlify/cli#1386] opened 2020-10-13 18:30 UTC
When running `netlify dev`, local root .env variables are overwritten by the Netlify variables pulled from my production settings (Site settings > Build & deploy > Environment > Environment variables). This is at least true for the variables that I need to be accessible in the browser with the NEXT_PUBLIC_ prefix ([blog post](https://nextjs.org/blog/next-9-4#new-environment-variables-support)).

My .env file contains (my file is actually 'env.local' but I reproduced this with .env):
```
NEXT_PUBLIC_PAYPAL_ENV=sandbox
```

My production settings contain: `NEXT_PUBLIC_PAYPAL_ENV=production`. The browser value of `process.env.NEXT_PUBLIC_PAYPAL_ENV` ends up being `production` when running `netlify dev`. I have confirmed that other NEXT_PUBLIC_ variables _not_ set in production are still correct in the browser when running locally, so the problem lies with Netlify.

I have to work around this by creating a new, dev-specific environment variable that takes precedence over the one shared between development and production. This is the code I use in my React component to avoid the issue:
```
let env = process.env.NEXT_PUBLIC_PAYPAL_ENV_DEV;
if (!env) {
    env = process.env.NEXT_PUBLIC_PAYPAL_ENV;
}
```

I don't think it's relevant here but this is my netlify.toml:
```
[build]
publish = "out/"
functions = "functions/"

[dev]
command = "npm run dev"

```

Here's my netlify dev output. What's interesting to me is that the next.js environment variable load does appear later in the sequence, but maybe it chooses not to override existing values.
```
>netlify dev
◈ Netlify Dev ◈
◈ Injected addon env var: FAUNADB_ADMIN_SECRET
◈ Injected addon env var: FAUNADB_SERVER_SECRET
◈ Injected addon env var: FAUNADB_CLIENT_SECRET
◈ Injected build setting env var: NEXT_PUBLIC_PAYPAL_ENV
◈ Injected build setting env var: NODE_ENV
◈ Overriding command with setting derived from netlify.toml [dev] block: npm run dev
◈ Functions server is listening on 60715
◈ Starting Netlify Dev with next

> learn-starter@0.1.0 dev C:\Users\ercgr\Documents\UrbanBasic\creator
> next dev

Loaded env from C:\Users\ercgr\Documents\UrbanBasic\creator\.env.local
ready - started server on http://localhost:3000

   ┌─────────────────────────────────────────────────┐
   │                                                 │
   │   ◈ Server now ready on http://localhost:8888   │
   │                                                 │
   └─────────────────────────────────────────────────┘

event - compiled successfully

```

**Comment by ercgrat** [comment] 2020-10-15 17:06
Just documenting for the sake of it...

Confirmed this is the root cause of a different issue I'm encountering with material UI server-side rendering.  There is a [common issue](https://github.com/vercel/next.js/issues/4249) of mismatch between client classes and server-rendered classes that I've already fixed using [the recommended solution](https://github.com/mui-org/material-ui/tree/master/examples/nextjs). Haven't had issues when running  `next dev`, but `netlify dev` reintroduces the issue. Injecting NODE_ENV=production causes a mismatch between the SSR output and the browser's expectations.

```
Warning: Prop `className` did not match. Server: "jss11" Client: "PrivateSwitchBase-input-11"
    in input (created by ForwardRef(SwitchBase))
    in span (created by ForwardRef(IconButton))
    in span (created by ForwardRef(ButtonBase))
    in ForwardRef(ButtonBase) (created by WithStyles(ForwardRef(ButtonBase)))
    in WithStyles(ForwardRef(ButtonBase)) (created by ForwardRef(IconButton))
    in ForwardRef(IconButton) (created by WithStyles(ForwardRef(IconButton)))
    in WithStyles(ForwardRef(IconButton)) (created by ForwardRef(SwitchBase))
    in ForwardRef(SwitchBase) (created by WithStyles(ForwardRef(SwitchBase)))
    in WithStyles(ForwardRef(SwitchBase)) (created by ForwardRef(Radio))
    in ForwardRef(Radio) (created by WithStyles(ForwardRef(Radio)))
    in WithStyles(ForwardRef(Radio)) (created by ThemedRadio)
    in label (created by ForwardRef(FormControlLabel))
    in ForwardRef(FormControlLabel) (created by WithStyles(ForwardRef(FormControlLabel)))
    in WithStyles(ForwardRef(FormControlLabel)) (created by ThemedRadio)
    in ThemedRadio (created by ThemedRadioGroup)
    in div (created by ForwardRef(FormGroup))
    in ForwardRef(FormGroup) (created by WithStyles(ForwardRef(FormGroup)))
    in WithStyles(ForwardRef(FormGroup)) (created by ForwardRef(RadioGroup))
    in ForwardRef(RadioGroup) (created by ThemedRadioGroup)
    in fieldset (created by ForwardRef(FormControl))
    in ForwardRef(FormControl) (created by WithStyles(ForwardRef(FormControl)))
    in WithStyles(ForwardRef(FormControl)) (created by ThemedRadioGroup)
    in ThemedRadioGroup (created by PositionRadioGroup)
    in PositionRadioGroup (created by Customizer)
    in div (created by Customizer)
    in div (created by Customizer)
    in Customizer (created by Home)
    in div (created by ForwardRef(CardContent))
    in ForwardRef(CardContent) (created by WithStyles(ForwardRef(CardContent)))
    in WithStyles(ForwardRef(CardContent)) (created by Page)
    in div (created by ForwardRef(Paper))
    in ForwardRef(Paper) (created by WithStyles(ForwardRef(Paper)))
    in WithStyles(ForwardRef(Paper)) (created by ForwardRef(Card))
    in ForwardRef(Card) (created by WithStyles(ForwardRef(Card)))
    in WithStyles(ForwardRef(Card)) (created by Page)
    in main (created by Page)
    in div (created by Page)
    in Page (created by Home)
    in Home (created by App)
    in ThemeProvider (created by App)
    in App
    in ErrorBoundary (created by ReactDevOverlay)
    in ReactDevOverlay (created by Container)
    in Container (created by AppContainer)
    in AppContainer
    in Root
```

**Comment by WensleyD** [comment] 2020-10-16 08:26
I'm experiencing a similar issue, it seems since v2.65.0 netlify dev isn't seeing the .env file for me.

**The following expected line in the terminal is missing: (Should be just below env var injections)**
```
◈ Overriding the following env variables with .env file: VUE_APP_SANITY_DATASET,VUE_APP_STRIPE_PUBLISHABLE_KEY,STRIPE_SECRET_KEY
```

Downgrading to v2.64.1 fixed the issue for me. The change log shows edits to this functionality. Maybe a break?

**Comment by amos80m** [comment] 2020-10-27 16:10
Adding this to _app.js helped me:
`React.useEffect(() => {
    // Remove the server-side injected CSS.
    const jssStyles = document.querySelector('#jss-server-side')
    if (jssStyles) {
      jssStyles.parentElement.removeChild(jssStyles)
    }
  }, [])`

**Comment by erezrokah** [comment] 2020-10-29 17:29
Hi 👋  Sorry for the late reply on this. This should be fixed in https://github.com/netlify/cli/pull/1490.
I wanted to some refactoring to make env var handing code more straightforward before fixing this.
Hopefully that would make it easier to avoid such bugs in the future.

**Closed** 2020-11-02 18:16 UTC
Labels: area: command: dev, type: bug

**Comment by ercgrat** [comment] 2020-11-29 14:50
@erezrokah I am still experiencing this issue in v2.69 when I remove the workaround that I describe above.

**Comment by erezrokah** [comment] 2020-11-30 13:50
Thanks for following up @ercgrat. Can you verify you're not experiencing  https://github.com/netlify/cli/issues/1596#issuecomment-733943220?

If that's not the case, can you share a reproduction (possibly in a repo)?

**Comment by ercgrat** [comment] 2020-11-30 14:25
> Thanks for following up @ercgrat. Can you verify you're not experiencing [#1596 (comment)](https://github.com/netlify/cli/issues/1596#issuecomment-733943220)?
> 
> If that's not the case, can you share a reproduction (possibly in a repo)?

Confirming that the variable is not set at the shell level.

Here's my [repo](https://github.com/ercgrat/creator.urbanbasic.de). I think it should be straightforward to install and run but let me know if you have issues. The variable in question is `NEXT_PUBLIC_PAYPAL_ENV` which I set in `env.local`. The app will crash without a DB token in your env.local but I don't think you need that to test this issue.

**Comment by erezrokah** [comment] 2020-11-30 14:58
> which I set in `env.local`.

We don't read `env.local` at the moment, only `.env.development` and `.env`:
https://github.com/netlify/cli/blob/66fd64c0da3756ec6f91ed6c8f7f5f00883a882a/src/utils/dot-env.js#L10

**Comment by ercgrat** [comment] 2020-11-30 15:01
> > which I set in `env.local`.
> 
> We don't read `env.local` at the moment, only `.env.development` and `.env`:
> https://github.com/netlify/cli/blob/66fd64c0da3756ec6f91ed6c8f7f5f00883a882a/src/utils/dot-env.js#L10

Got it, well at least that was easy. For my purpose, it doesn't matter. That said, `env.local` has a special function in Next.js and it will not always be possible to replicate desired behavior using .env or .env.development. See [docs](https://nextjs.org/docs/basic-features/environment-variables). Would be worth writing an issue to add support for `env.local`.
