### ISSUE TITLE
Unhelpful error: TypeError: Cannot read property '0' of   undefined

### ISSUE THREAD

**Issue by sw-yx** [netlify/cli#2557] opened 2021-06-06 17:29 UTC
**Describe the bug**

typing in `ntl deploy --prod` gets this:

```
Deploy path:        /Users/swyx/Work/swyxdotio/public
Configuration path: /Users/swyx/Work/swyxdotio/netlify.toml
Deploying to main site URL...
 ›   Warning: 
 ›   {}
 ›
    TypeError: Cannot read property '0' of
     undefined
```

I've never seen this error before as a heavy netlify user. netlify console displayed this

![CleanShot 2021-06-07 at 01 30 07](https://user-images.githubusercontent.com/6764957/120934195-ebe55e00-c72f-11eb-9e73-dc60d99ea92c.png)

When I reran `ntl deploy`, it worked again. I think there is some bad error handling inside of the CLI but cant tell more because the stack trace is swallowed.

**Configuration**

- If possible, please copy/paste below your `netlify.toml`.

```
[build]
  command = "yarn build"
  publish = "public/"

[[headers]]
  for = "/dist/svelte/*"
  [headers.values]
    cache-control = '''
      public,
      max-age=31536000,
      immutable'''
```

- Please enter the following command in a terminal and copy/paste its output:

```bash
npx envinfo --system --binaries --npmPackages netlify-cli --npmGlobalPackages netlify-cli
```

```

  System:
    OS: macOS 11.3.1
    CPU: (8) x64 Apple M1
    Memory: 32.25 MB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 15.5.0 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 7.3.0 - /usr/local/bin/npm
  npmGlobalPackages:
    netlify-cli: 3.21.10
```

**Comment by erezrokah** [comment] 2021-06-06 17:36
Thanks for opening the issue @sw-yx ❤️ 
I believe this is somehow a duplicate of #2086.
In #2086 the error was coming from our `js-client`, but since then https://github.com/netlify/js-client/issues/157 was resolved, so now the offending code is part of the CLI.

Moving the code to the CLI **_should_** allow us to better debug this once we follow up on #2086 with some more refactoring.

Keeping the issue open for now.

**Comment by eduardoboucas** [comment] 2021-06-07 13:58
@ascorbic is this the error you were seeing?

**Comment by ascorbic** [comment] 2021-06-07 14:05
@eduardoboucas  Yes, it is. It's intermittent, when I was running `ntl deploy --build`

**Comment by sw-yx** [comment] 2021-06-07 15:27
interesting. i think itd be good to identify the part of the CLI that is throwing this error and showing the rest of the stack trace. in general ive started to dislike swallowing stack traces... it reduces our ability to debug or even report issues. perhaps worth scanning thru the codebase for `console.error` and making sure things are thrown properly instead of swallowed

**Comment by erezrokah** [comment] 2021-06-07 15:36
💯  to not swallowing stack traces. I believe we are mostly using the `oclif` `this.error` utility to report errors and exit so I have a feeling that's the culprit but I'll need to investigate more.

**Closed** 2021-06-07 16:23 UTC
Labels: area: command: deploy, status: duplicate, type: bug

**Comment by erezrokah** [comment] 2021-06-07 16:59
This should be fixed in the next release.
As for swallowing errors, that is coming from `oclif` here:
https://github.com/oclif/errors/blob/4aa3941839812523bec265c93333e166ce71bbed/src/handle.ts#L18
https://github.com/oclif/errors/blob/4aa3941839812523bec265c93333e166ce71bbed/src/errors/pretty-print.ts#L55
and can be overridden  via ` DEBUG='*' ntl deploy`.

We can also enable `debug` in [`oclif` config](https://oclif.io/docs/config), but I tested it a bit and it seems too verbose.
