### ISSUE TITLE
Decrease amount of installed dependencies

### ISSUE THREAD

**Issue by Leksat** [netlify/cli#6026] opened 2023-09-25 16:50 UTC
### Which problem is this feature request solving?

Adding `netlify-cli` to a project brings in 1k of npm dependencies.
```
$ pnpm init
Wrote to package.json
...

$ pnpm i netlify-cli
...
Progress: resolved 1053, reused 874, downloaded 147, added 1021, done
...
dependencies:
+ netlify-cli 16.4.2
...
```

### Describe the solution you'd like

Is it maybe possible to pack `netlify-cli` with `rollup` bundling in all/most of dependencies?

### Pull request (optional)

- [ ] I can submit a pull request.

**Comment by sarahetter** [comment] 2023-09-25 20:26
Closing as duplicate of https://github.com/netlify/cli/issues/3941

**Closed by sarahetter** 2023-09-25 20:26 UTC
Labels: type: feature
