### ISSUE TITLE
netlify login not working

### ISSUE THREAD

**Issue by ishaquee** [netlify/cli#1799] opened 2021-01-24 07:31 UTC
I am Successfully installed netlify on my pc via this command: " npm install netlify-cli -g " .
after that refresh my terminal and try to run this command: " netlify login " its show error like this :  'netlify' is not recognized as an internal or external command,  operable program or batch file. ".
I am not able to access it locally .

Thanks

**Comment by eduardoboucas** [comment] 2021-01-25 10:06
Hi @ishaquee! This seems to be a duplicate of #1088 — if you don't mind, I'll close this issue and we can move the conversation there.

In particular, can you try the suggested workaround in https://github.com/netlify/cli/issues/1088#issuecomment-674264546?

Thanks.

**Closed by eduardoboucas** 2021-01-25 10:06 UTC
Labels: type: bug

**Comment by ishaquee** [comment] 2021-01-25 13:54
Hey there .
I am tried all possible ways but  I don't know why in my system Netlify not
working ?

Did u help me ?

**Comment by eduardoboucas** [comment] 2021-01-25 14:04
Just checking that you saw [my previous comment](https://github.com/netlify/cli/issues/1799#issuecomment-766703098)?

**Comment by ishaquee** [comment] 2021-01-25 15:51
Hello there.
I tried above method but i am not able run Netlify locally.
Please help me solve this

**Comment by ishaquee** [comment] 2021-01-25 16:12
Hello there.
Please help me to resolve this error.
I am not able to access Netlify locally.

**Comment by ishaquee** [comment] 2021-01-25 16:13
I tried all command but unfortunately not working .
Help me there please

**Comment by erezrokah** [comment] 2021-01-26 10:11
Hi @ishaquee sorry for the issues you're having.
We need a bit more information to identify the cause for the issues.
Can you:
1. Share the output of `npx envinfo --system --binaries --npmPackages netlify-cli --npmGlobalPackages netlify-cli`
2. Run `netlify logout` and share the output of the result
3. Run `netlify login` and share the output of the result (a browser window should open asking you to authorize the CLI)
4. Run `netlify status` and share the result

**Comment by ishaquee** [comment] 2021-01-26 10:35
1) npx envinfo --system --binaries --npmPackages netlify-cli
--npmGlobalPackages netlify-cli

npx: installed 1 in 78.577s
(node:8184) UnhandledPromiseRejectionWarning: Error: Command failed: wmic
os get Caption
'wmic' is not recognized as an internal or external command,
operable program or batch file.


    at b
(C:\Users\ELCOT\AppData\Roaming\npm-cache\_npx\8184\node_modules\envinfo\dist\envinfo.js:1:95039)
    at Function.e.exports.sync
(C:\Users\ELCOT\AppData\Roaming\npm-cache\_npx\8184\node_modules\envinfo\dist\envinfo.js:1:96902)
    at e.exports
(C:\Users\ELCOT\AppData\Roaming\npm-cache\_npx\8184\node_modules\envinfo\dist\envinfo.js:1:93256)
    at e.exports
(C:\Users\ELCOT\AppData\Roaming\npm-cache\_npx\8184\node_modules\envinfo\dist\envinfo.js:1:92403)
    at
C:\Users\ELCOT\AppData\Roaming\npm-cache\_npx\8184\node_modules\envinfo\dist\envinfo.js:1:91153
    at async Promise.all (index 0)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:8184) UnhandledPromiseRejectionWarning: Unhandled promise rejection.
This error originated either by throwing inside of an async function
without a catch block, or by rejecting a promise which was not handled with
.catch(). To terminate the node process on unhandled promise rejection, use
the CLI flag `--unhandled-rejections=strict` (see
https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection
id: 1)
(node:8184) [DEP0018] DeprecationWarning: Unhandled promise rejections are
deprecated. In the future, promise rejections that are not handled will
terminate the Node.js process with a non-zero exit code.

----------------------------------------------
2)    C:\Users\ELCOT>netlify logout
'netlify' is not recognized as an internal or external command,
operable program or batch file.

-------------------------------
3)    C:\Users\ELCOT>netlify login
'netlify' is not recognized as an internal or external command,
operable program or batch file.

-----------------------------------------
4)   C:\Users\ELCOT>netlify status
'netlify' is not recognized as an internal or external command,
operable program or batch file.

**Comment by erezrokah** [comment] 2021-01-26 11:49
Hi @ishaquee thanks for the additional information - that helps.
This issue seems like a duplicate of https://github.com/netlify/cli/issues/1088#issuecomment-673561868.

Can you share the result of running:
1. `npm install netlify-cli -g`
2. `node --version`
3. `npm --version`

**Comment by ishaquee** [comment] 2021-01-26 12:08
----------------------------------------------------------------------

npm install netlify-cli -g

npm WARN deprecated urix@0.1.0: Please see
https://github.com/lydell/urix#deprecated
npm WARN deprecated resolve-url@0.2.1:
https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated rollup-plugin-inject@3.0.2: This package has been
deprecated and is no longer maintained. Please use @rollup/plugin-inject.
C:\Users\ELCOT\AppData\Roaming\npm\netlify ->
C:\Users\ELCOT\AppData\Roaming\npm\node_modules\netlify-cli\bin\run
C:\Users\ELCOT\AppData\Roaming\npm\ntl ->
C:\Users\ELCOT\AppData\Roaming\npm\node_modules\netlify-cli\bin\run

> netlify-cli@3.4.2 postinstall
C:\Users\ELCOT\AppData\Roaming\npm\node_modules\netlify-cli
> node ./scripts/postinstall.js


Success! Netlify CLI has been installed!

Your device is now configured to use Netlify CLI to deploy and manage your
Netlify sites.

Next steps:

  netlify init     Connect or create a Netlify site from current directory
  netlify deploy   Deploy the latest changes to your Netlify site

For more information on the CLI run netlify help
Or visit the docs at https://cli.netlify.com

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.1.2
(node_modules\netlify-cli\node_modules\rollup\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for
fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current:
{"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY:
@netlify/traffic-mesh-agent-darwin-x64@^0.27.10
(node_modules\netlify-cli\node_modules\@netlify\traffic-mesh-agent\node_modules\@netlify\traffic-mesh-agent-darwin-x64):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for
@netlify/traffic-mesh-agent-darwin-x64@0.27.10: wanted
{"os":"darwin","arch":"x64"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY:
@netlify/traffic-mesh-agent-linux-x64@^0.27.10
(node_modules\netlify-cli\node_modules\@netlify\traffic-mesh-agent\node_modules\@netlify\traffic-mesh-agent-linux-x64):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for
@netlify/traffic-mesh-agent-linux-x64@0.27.10: wanted
{"os":"linux","arch":"x64"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.3.1
(node_modules\netlify-cli\node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for
fsevents@2.3.1: wanted {"os":"darwin","arch":"any"} (current:
{"os":"win32","arch":"x64"})
npm WARN @octokit/plugin-request-log@1.0.3 requires a peer of @octokit/core@>=3
but none is installed. You must install peer dependencies yourself.

+ netlify-cli@3.4.2
added 23 packages from 19 contributors and updated 15 packages in 365.776s
-------------------------------------------------

C:\Users\ELCOT>node --version
v13.14.0

----------------------------------------------------------

C:\Users\ELCOT>npm --version
6.14.10

**Comment by erezrokah** [comment] 2021-01-26 12:50
Hi @ishaquee this does seem like the issue in https://github.com/netlify/cli/issues/1088.

I suggest we track it under that issue, I'll comment on that one

**Comment by ishaquee** [comment] 2021-01-26 17:57
Hello there.

Now I am what to do ?
