### ISSUE TITLE
ntl init error: TypeError: undefined is not iterable

### ISSUE THREAD

**Issue by jmsherry** [netlify/cli#5018] opened 2022-08-31 00:41 UTC
### Describe the bug

When running ntl init I get the error: `TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))`

This occurs particularly when trying to create the functions directory.

### Steps to reproduce

1. Run `ntl init` and accept the default options

`❯ node -v
v16.8.0
❯ ntl init
? What would you like to do? +  Create & configure a new site
? Team: James Sherry's team
Choose a unique site name (e.g. super-cool-site-by-jmsherry.netlify.app) or leave it blank for a random name. You can update the site name later.
? Site name (optional): test-ttt

Site Created

Admin URL: https://app.netlify.com/sites/test-ttt
URL:       https://test-ttt.netlify.app
Site ID:   b4fc1a25-ba7f-4a09-84d5-7227139fac15
? Your build command (hugo build/yarn run build/etc): # no build command
? Directory to deploy (blank for current dir): public
? Netlify functions folder: netlify/functions
? No netlify.toml detected. Would you like to create one with these build settings? Yes
    TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))`

### Configuration

# example netlify.toml
[build]
  command = "# no build command"
  functions = "netlify/functions"
  publish = "public"

  ## Uncomment to use this redirect for Single Page Applications like create-react-app.
  ## Not needed for static site generators.
  #[[redirects]]
  #  from = "/*"
  #  to = "/index.html"
  #  status = 200

  ## (optional) Settings for Netlify Dev
  ## https://github.com/netlify/cli/blob/master/docs/netlify-dev.md#project-detection
  #[dev]
  #  command = "yarn start" # Command to start your dev server
  #  port = 3000 # Port that the dev server will be listening on
  #  publish = "dist" # Folder with the static content for _redirect file

  ## more info on configuring this file: https://www.netlify.com/docs/netlify-toml-reference/

### Environment

  System:
    OS: macOS 12.5
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 44.93 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.8.0 - /var/folders/hd/jkczj0nx7zb6xywcm3x9hbn80000gn/T/fnm_multishells/46810_1661895578892/bin/node
    Yarn: 1.22.18 - /usr/local/bin/yarn
    npm: 7.21.0 - /var/folders/hd/jkczj0nx7zb6xywcm3x9hbn80000gn/T/fnm_multishells/46810_1661895578892/bin/npm
    Watchman: 2022.03.21.00 - /usr/local/bin/watchman
  npmPackages:
    netlify-cli: ^11.5.1 => 11.5.1 
  npmGlobalPackages:
    netlify-cli: 11.5.1

**Comment by tinfoil-knight** [comment] 2022-09-24 13:45
@jmsherry Could you update the Netlify CLI package & try again once? I'm not able to reproduce this issue.

If the issue is still occurring, could you provide a repository in the original state (before running the `init` command)?

**Comment by tinfoil-knight** [comment] 2022-11-26 13:22
Closing this issue as it's no longer reproducible with `netlify-cli/12.2.7`.

**Closed by tinfoil-knight** 2022-11-26 13:22 UTC
Labels: type: bug
