### ISSUE TITLE
Netlify deploy with build flag uses different directory

### ISSUE THREAD

**Issue by bronze** [netlify/cli#5036] opened 2022-09-09 02:57 UTC
### Describe the bug

`netlify deploy` and `netlify build` commands are working correctly
however, doing `netlify deploy --build` uses a wrong deploy path.

netlify deploy:
```
Deploy path:        /home/bronze/coding/gold/dist
Configuration path: /home/bronze/coding/gold/netlify.toml
```

netlify deploy --build
```
Deploy path:        /home/bronze/coding/gold/astro build
Configuration path: /home/bronze/coding/gold/netlify.toml
```

Honestly i dont know ehere that `astro build` is coming from

### Steps to reproduce

Tried reverting to version `11.5.1` and everything worked.
Caught this discrepancy:
11.6.0
```
  1. build.command from netlify.toml
────────────────────────────────────────────────────────────────
​$ astro build
```
11.5.1
```
 1. build.command from netlify.toml
────────────────────────────────────────────────────────────────
​$ pnpm build || ( npm install pnpm && pnpm build )
```
I dont even have `astro build` on my `netlify.toml`. Changed the command on my package.json too and it didnt change, so im not sure where it is getting this command from.

### Configuration

```
[build.environment]
  NODE_VERSION = "16"

[build]
  publish = "dist"
  command = "pnpm build || ( npm install pnpm && pnpm build )"

[dev]
  autoLaunch = false
  command = "pnpm run dev"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
```

### Environment

```
  System:
    OS: Linux 5.10 Ubuntu 20.04.4 LTS (Focal Fossa)
    CPU: (12) x64 AMD Ryzen 5 3600X 6-Core Processor
    Memory: 21.98 GB / 25.02 GB
    Container: Yes
    Shell: 5.8 - /usr/bin/zsh
  Binaries:
    Node: 16.13.0 - ~/.nvm/versions/node/v16.13.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v16.13.0/bin/yarn
    npm: 8.19.1 - ~/.nvm/versions/node/v16.13.0/bin/npm
  npmGlobalPackages:
    netlify-cli: 11.6.0
```

**Comment by tinfoil-knight** [comment] 2022-09-21 13:13
@bronze Is the repository public? Otherwise, could you provide a minimal reproducible example?

**Comment by bronze** [comment] 2022-09-21 15:48
Hi @tinfoil-knight 
Just made a fresh new repo at https://github.com/bronze/netlify-cli-bug and i can confirm i still get this bug with the 11.8.2 version

It only happens when running build AND deploy. I think it may have something to do with the [framework detection ](https://github.com/netlify/cli/pull/5029)from 11.6
11.5.1
```
> netlify deploy --prod --build

────────────────────────────────────────────────────────────────
  Netlify Build                                                 
────────────────────────────────────────────────────────────────

❯ Version
  @netlify/build 27.16.1

❯ Flags
  {}

❯ Current directory
  /home/bronze/coding/netlify-cli-bug

❯ Config file
  /home/bronze/coding/netlify-cli-bug/netlify.toml

❯ Context
  production

────────────────────────────────────────────────────────────────
  1. build.command from netlify.toml                            
────────────────────────────────────────────────────────────────

$ pnpm build || ( npm install pnpm && pnpm build )

...

(Netlify Build completed in 2.4s)
Deploy path:        /home/bronze/coding/netlify-cli-bug/dist
Functions path:     /home/bronze/coding/netlify-cli-bug/netlify/functions
Configuration path: /home/bronze/coding/netlify-cli-bug/netlify.toml
```
11.8.2
```
> netlify deploy --prod --build

────────────────────────────────────────────────────────────────
  Netlify Build                                                 
────────────────────────────────────────────────────────────────

❯ Version
  @netlify/build 27.18.4

❯ Flags
  {}

❯ Current directory
  /home/bronze/coding/netlify-cli-bug

❯ Config file
  /home/bronze/coding/netlify-cli-bug/netlify.toml

❯ Context
  production

────────────────────────────────────────────────────────────────
  1. build.command from netlify.toml                            
────────────────────────────────────────────────────────────────

$ astro build

...

(Netlify Build completed in 2s)
Deploy path:        /home/bronze/coding/netlify-cli-bug/astro build
Functions path:     /home/bronze/coding/netlify-cli-bug/netlify/functions
Configuration path: /home/bronze/coding/netlify-cli-bug/netlify.toml
 ›   Error: No such directory /home/bronze/coding/netlify-cli-bug/astro build! Did you forget to run a build?
```

**Comment by dariodevito** [comment] 2022-09-23 14:12
It came in on this commit https://github.com/netlify/cli/commit/c85efc45bd46ee4038fbe44f64fe99ce0b25eb7b

Hence 11.5.1 working for @bronze

**Comment by tinfoil-knight** [comment] 2022-09-23 14:12
@dariodevito Thank you for finding out the potential cause. I debugged @bronze's site independently & found the issue occurring at the mentioned line.

@sarahetter This issue seems to be originating in this PR: https://github.com/netlify/cli/pull/5029

The `publish` variable (which originally had the location of the build directory) is being overwritten by the build command.

Could you please take a look?

**Comment by tinfoil-knight** [comment] 2022-09-24 10:22
@bronze

Closing this as it has been resolved in https://github.com/netlify/cli/pull/5084. 

Please update the Netlify CLI package to `v11.8.3`.

---

Thank you @sarahetter for the super-quick fix.

**Closed by tinfoil-knight** 2022-09-24 10:22 UTC
Labels: type: bug
