### ISSUE TITLE
Process Loop / Memory Leak

### ISSUE THREAD

**Issue by Palgie** [netlify/cli#511] opened 2019-09-04 13:42 UTC
Hello Netlify Contributors 👋

I'd been trailing Netlify lambda via Netlify CLI's `dev` command testing a simple Mailchimp API interface. I never got to testing the code so please excuse any syntax errors but It appears that when `netlify dev` picks up the Lambda it causes an endless loop of netlify lambda processes in the background which quickly leads to a complete machine crash. I'd replicated multiple times and it only occurs when the below Lambda is present in the functions source directory.

The Lambda itself is:
```javascript
var Mailchimp = require('mailchimp-api-v3')
var headers = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "Content-Type"
}

var mailchimp = new Mailchimp(process.env.MAILCHIMP_API);

exports.handler = async (event, context) => {
  mailchimp.get({
    path : '/lists/<id>'
  }, function (err, result) {
    return {
      statusCode: 200,
      headers,
      body: JSON.stringify({
        status: "it works! beep boop",
        result
      })
    }
  })
};
```

Note that `<id>` here is just for the example and is replaced by an actual ID.

I realise now that after hitting the issues pages of the repo here that it's recommended not to use subdirectories which I guess Increases the unreliability. Before knowing this though I'd attempted to add the dependency via package.json and place the lambda under this format: `/functions/<lambda>/<lambda.js>` alongside a `package.json` to isolate package dependency to the particular Lambda. Upon moving to that folder structure while `netlify dev` is running the host machine quickly drains memory and CPU and crashes the host and the result of `ps aux` is below. In my case my machine is a macOS.

<img width="1347" alt="netlify-lambda" src="https://user-images.githubusercontent.com/725626/64258810-7943bf00-cf5a-11e9-9ae5-0ab71cef6f2f.png">

_Note:_ The empty blanks here are just image edits. Screenshot is after ~5 minutes after a fresh boot where no other `netlify dev` processes had run.

The versions used here are:
- netlify-cli/2.12.0
- darwin-x64
- node-v12.9.1
- netlify-lambda-v1.6.3

**Comment by Palgie** [comment] 2019-09-05 14:43
Thanks @sw-yx

**Comment by ryan-gilb** [comment] 2019-12-31 18:40
👋 Hey all! Chiming in here, I'm also having this issue. I have a `functions` folder in the root of my project, and a `functions/lib` folder to support my `functions/graphql.js` file. I use `netlify-lambda` to build and install dependencies local to my function, and I currently use it to serve the function locally as well. I've been able to verify that my function works properly locally, as well as when it's deployed to Netlify; I'm only seeing this issue when running it with `netlify dev`.

Thankfully I can still use `netlify-lambda` to develop locally, but I'd love to get on board with `netlify dev`, and if there's any more diagnostic info or help I could provide, let me know!

Thanks 😄

**Comment by RaeesBhatti** [comment] 2020-04-13 23:52
@Palgie @ryan-gilb I think this should've been fixed in the latest version. Can you please update your `netlify-cli` to the latest version and let us know!

**Comment by Palgie** [comment] 2020-04-15 13:31
Thanks @RaeesBhatti - will let you know if I get the chance to confirm this.

**Comment by ryan-gilb** [comment] 2020-04-25 18:13
Hey @RaeesBhatti, I updated my `netlify-cli`. This is the output of `netlify --version`: `netlify-cli/2.48.0 darwin-x64 node-v10.16.3`. I'm still experiencing the original issue. I'm probably doing something funky in my lambda, but I'll just keep using `netlify-lambda` for now 🙂

**Comment by seawatts** [comment] 2020-06-09 04:47
I'm seeing a similar issue

**Comment by erezrokah** [comment] 2020-08-20 14:32
Related to https://github.com/netlify/cli/issues/904 and should have been fixed in https://github.com/netlify/cli/pull/974.
Please comment if still an issue with the latest version

**Closed by erezrokah** 2020-08-20 14:32 UTC

**Comment by awacode21** [comment] 2021-07-29 20:25
I think i could have the same problem. But maybe it's wrong usage on my side.
When using netlify-dev and opening the browser to test within my application the netlify function is called again and again. I aborted it after 2225 times.
When i test my netlify function using netlify functions:invoke everything ist totally fine!! But as soon as i use it in my application with axios there is an endless loop.

My Configuration:

api/functions/main-navigation/main-navigation.js
`require('dotenv').config();
const axios = require('axios');

const { STORYBLOK_API_URL, STORYBLOK_API_TOKEN } = process.env;

const handler = async (event) => {
  const { ...params } = event.queryStringParameters;
  const paramsString = Object.keys(params).map(key => `${key}=${params[key]}`).join("&");
  const requestUrl = `${STORYBLOK_API_URL}stories/main_navigation?token=${STORYBLOK_API_TOKEN}&${paramsString}`;
  
  try {
    const response = await axios.get(requestUrl);
    return {
      statusCode: 200,
      body: JSON.stringify(response.data),
    }
  } catch (error) {
    return { statusCode: error.statusCode, data: error.toString() }
  }
}

module.exports = { handler }
`

netlify.toml
`[build]
  command = "npm run generate"
  functions = "api/functions"
  publish = "dist"

[dev]
  command = "npm run dev"
  publish = "dist"
  autoLaunch = true
  `
  
  Usage in my application:
  `export const actions: ActionTree<MainNavigationState, RootState> = {
    async loadNavigation({ commit }, context) {
        await this.$axios.$get('/.netlify/functions/main-navigation?resolve_links=url&language=de&version=published')
        .then((data) => {
            commit('setMainNavigation', data.story.content.main_navigation);
        }).catch((error) => {
            handleStoryblokError(error, context);
        });
    },
};`

Any idea?

Best regards, Annick

**Comment by erezrokah** [comment] 2021-08-02 12:09
Hi @awacode21, do you mind opening a new issue for that? Please include a reproduction scenario if possibly as it we'll help us identity the root cause much faster.

**Comment by awacode21** [comment] 2021-08-02 13:09
i found a way to fix my loop problem. When using axios in my store action but node-fetch within the netlify functions and also adding a baseUrl for the axios config in nuxt.config.js it fixed the infinite loop. I guess somehow an axios call within an axios call with missin base url was causing the issue. I don't exactly understand why, but it fixes it for my case. No loops anymore!
