### ISSUE TITLE
netlify dev --live: Media / MP4 serving error

### ISSUE THREAD

**Issue by robotastic** [netlify/cli#467] opened 2019-04-11 20:28 UTC
There is an error working with .mp4 files. I am trying to use the live plugin with the Restaurant Hugo demo site: https://github.com/netlify/restaurant-template-cms that is in the JAMStack tutorial: https://www.netlify.com/blog/2017/10/06/coding-modern-websites-with-the-jamstack-part-1/

It has a number of .MP4 files that are shown in the template and the local server returns the following error trying to server them:

`
/usr/local/lib/node_modules/netlify-cli/node_modules/netlify-redirector/lib/redirects.js:116
      throw ex;
      ^

Error: Parse Error
    at Socket.socketOnData (_http_client.js:442:20)
    at Socket.emit (events.js:189:13)
    at addChunk (_stream_readable.js:284:12)
    at readableAddChunk (_stream_readable.js:265:11)
    at Socket.Readable.push (_stream_readable.js:220:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:94:17)
ERRO[0013] Failed to do http request to local service    error="Get http://localhost:8888/videos/SDVid.mp4: EOF" request_id=d0001618-6bb2-4e3a-9604-19f7378de713`

**Comment by erezrokah** [comment] 2021-04-25 12:23
This is unrelated to `--live` and also doesn't work without the `--live` flag.
To fix it:
1. `npm install natives@1.1.6` (required to fix `gulp` on Node.js >=10). See [here](https://github.com/gulpjs/gulp/issues/2246)
2. Add the following to `netlify.toml`
```toml
[dev]
command = "npm run start"
framework = "#custom"
targetPort = 3000
```
3. `netlify dev --live` should work

Closing. Please comment if the issue is still relvant.

**Closed by erezrokah** 2021-04-25 12:23 UTC
Labels: area: command: dev, area: dev-live, type: bug
