### ISSUE TITLE
Error on post install script

### ISSUE THREAD

**Issue by mrloop** [netlify/cli#3981] opened 2022-01-09 10:26 UTC
**Describe the bug**

`yarn global add netlify-cli` fails with 

```
2022-01-09T06:12:14.3245718Z Command: node ./scripts/postinstall.js
2022-01-09T06:12:14.3246467Z Arguments: 
2022-01-09T06:12:14.3247497Z info Visit https://yarnpkg.com/en/docs/cli/global for documentation about this command.
2022-01-09T06:12:14.3253330Z Directory: /home/runner/.config/yarn/global/node_modules/netlify-cli
2022-01-09T06:12:14.3254522Z Output:
2022-01-09T06:12:14.3255630Z LIBERTY LIBERTY LIBERTY
2022-01-09T06:12:14.3256543Z LIBERTY LIBERTY LIBERTY
2022-01-09T06:12:14.3257372Z LIBERTY LIBERTY LIBERTY
2022-01-09T06:12:14.3262258Z                                    !             H|H|H|H|H           H__________________________________             H|§|§|§|H           H|* * * * * *|---------------------|             H|§|∞|§|H           H| * * * * * |---------------------|             H|§|§|§|H           H|* * * * * *|---------------------|             H|H|H|H|H           H| * * * * * |---------------------|             H|H|H|H|H           H|---------------------------------|          ===============        H|---------------------------------|            /| _   _ |          H|---------------------------------|            (| O   O |)          H|---------------------------------|            /|   U   |          H-----------------------------------             |  =/  |           H              _..._/            H              _|I/|_            H      _______/| H |/_______    H     /           / /          H    |          | | /         |  H    |          ||o||          |  H    |    |     ||o||     |    |  H    |    |     ||o||     |    |  H   Carl Pilcher  
2022-01-09T06:12:14.3274219Z ț̸̛̥͈̪͍̳̫̱͍͖̳̞̞̭̬̬̩̳͖͖͍̭͍̤͉͚̰͇͇̫̘̬̭̼͕̫̩̬̫͓͍̞̞͍̟̠͖͙̝̰̮͚̼̣͙̖͕͙͔͉͙͔͔̈͐ͮͨ̋̆̓̍̊ͣ̓̉̄͢͞ͅͅę̴͕͔̣̩̔͗̿̈ͬ̀̚͟͠s̡̧̛̻͉̫͙͎̟̤͉̩̙̭͚̬̦͖̮̠̠̜̗̺͍̀͊̏ͯͯ̚ţ̵̫̬̣͔̝͍̲͚̩͍̬̬͍͍͕̰̀ͦ̎ͮ̎̍̇͆͂̊̂ͅͅi̡̦̲͔̹̰̪͈̥͙̠͓͙͒͆͐ͥ̅͑ͨ̆̐ͪ̑̎̉̔̑͊͠͠ͅn̛͛ͬͧ͂͟͡ ҉̹̤̦͓͖̩͇̮̳̻̺̙̻̫͖͓͍̹̱̬̞͇̳̟̪̘͕̭̹̱̝̗̭͕̮̣̹̺̫̳̱͉̭̩̮̘̳͈̣͕̪͈͇̘̺̭̣g̴̴̛̗͔͉͎͙̞̙͚̱̩̟̟͔͓͓̟͉̠̱̱͖͎̲̳̞̺̰̭͖̱̥̬̝̥̤̝̖̝̣̰̤̰̣̩̙̲̟̜̞͙̞̝̯͉͇ͦ̎̈̊́͊ͨ͐ͦ͘͡ ̵̡͚͕͚̖̺̺͚͌͐͋̃͋̑͐͆̏̒͒̌ͪ̕͠t̨̧̟͍͓̤͇̣̥̤̮̞̰͚͖̮̙̪͖̮͚̪̮̭͎͓̹̻̝͈̲͓̱͎̲̗̝ͫ́̂̽̈ͭ̈͐̽̇̃ͩ͜͟͝ͅe̯͔̥͔̞̮̹̲̻̠̯̪̲̳͎̹̺̙͚̱̣͔͎̪͉͈̭̬̘̻̲̱̪̮͚̼͎̲̠͚̰̺͈͇̙͔̥͕͎̠̖͖͔̪͉͉̭̦̩̲͚̺͖̜̗ͥ̐̎̋̃͋ͯ̓̾ͦͤͣ͒̾̽̇̀͜s̸ͦ̽̓̔͑͆̾̑̽̉ͧͥ͋͌̊́ ҉͈̣̙̞̺̻̠̖̥̲̠̼̱̲̻̮̫̠̩̮̞̞̭͍͖͖̖̣̖̦͎̗̞͍͈̹̻̯̟̼̠͚̫̠͍̤̭͇͖̹͎̼͎̣̲͕̱̬̻̰̺̺͎̩̰̀̕ͅt͐ͯ̈͑ͦ̎̏͛̿̓̌̋͑ͧͥ̄ͣ̚ ҉̷̨̱̭̙͇̺̱͉̥̯̥̟̯͕̥̼͚̰̫̩̥̪̝͔͍̫̱̯̱͎̪̫̲̰̗̹̹͔̘̞͔̟͇̰̟̳͇̥͓̺̟̼̯̱͖͉̹̩͍̘͈͜͡ͅį̶̬̳̻͍̟͙͚̬͖̫͙͉̹͈̲͇̗̬̗͖̝͔͖̺͔̖̮̠̼͇̯͒͋̇͆̉̋ͫͩ̉͂̏ͯ̌̂̅̾̋͘͝͞ͅn̶̤̮̟͔̭̣̻͍̹̥̹͚͉͈̟̖̥̱̹͍̗̪̤̲̳͔̠̻̖̤̓͑̎̍̌̉̉̇ͮ͒ͫ̀̉́͛̆̀̚͟g̐̋͌̈ͦ͆ͩͯͭ̍̓̎ͧͮ̓ͥ̔̃͜͝ ҉͎̟̻͙̻̤̮̙̖͕͎̫̘̺̥̤̣̰̟͙̤͚͖̣̜̭̞̼̞̠̦͙͔̪͓̺̲̱͙͍̜̙̤̝̗̗̮͓̱̻͎̰̗̲̘̖͇̝̖̞̖ͅͅͅ ̅̏ͭ̐̀̔̈̂͒̉ͨ̍͜ ҉̢͉̰̙̠̻͉̙̼̭̯͇̰͖̬͎͓̘̖̲̜͈͖͖̖͙̟̦ţ̴̲͓͖̦̝̻̝͇͓͓͇̞̬̯̙̊͆̏ͤ̿̌ͥ̚͢͢͝ȩ̴̡ͪ̍̈̌̆̾̈͛̎͐͡ ҉͓̺̟̫͔͓̲̦̟͖̲͓̥̱̱̤͇̟̜̙̯̬̮̰̦͕̺̪̘͈̟̘̮̘̗̟̙̱̩̳̳͎̮̠̣͇̩̱͇̘͖̦͍͔͎̜͉ͅͅs̺͔̼̮̙̦͚̞͔͔̬̰̘ͩ͑́͋̎̾̀̚͘͘͡͠t̵̷ͤ̑̐̈͒ͭͮ̈ͥ͋̅́̽̾ ҉ ҉̯̼̞̦̫̠̳͍͙̮͔̜̥̠̲̳̗̘̭̬͓̲͚̱̟͖̺̞̪̻̫̹̲̥̹̖̜͍̰̻̲̣͕̞͈̠ͅï̧̯̬̖̗͍͕̰̮̼̮̗͎̭͉̗͉͚͓̠̖̳̟̦͚̲̬̼̩̝̮̲̘̉͆͌ͯͮ͛ͦ̈̍͌͆͒͋ͨ̂̇͜͡ņ̛̘̪͇̼̬̫̲͙͕͓̦̫͚͖͖̊ͦ͆ͦ̍͌̓̔ͥͧ̆́ͣͅg̢̭̰̜͈͎̫̰̫̫̜̥͖̭͙̗̦̺̦̤̬͇̗͎̘̯̯̩̙͉̳̖̠̯̽͆̈̑̈̄ͦ̊̊ͩ̾ͫ͢͠ͅ ̶̷̭̟̳͈̖̟͖͈͇͓͉̼̙̯̹̠͖͓̤̘͎͈̼̖̫̟̤̯̪̹̲̘̞̭̗̰̞͇̘̾́̈͛̊̽́̔͆ͬ̐̉̎͆ͫ̓̓̒ͩt̛̮͓͎̬̟̲͙̯̻̰̥̼͔̟̺̣̟͚̯͉͎̝̳͈̖͖̦̼̮͔̜̫̝͍̻̗̞̙̉ͨ͊ͧ̾ͣ͒̑͐̓ͯ̈ͯ̚̚͢͝ḗ̴̸̶̡̘̭͙͚̲͍̭͚̮̫̲̹̳̼̼̱̪͈̤̳͓̫̲͚̟̮̦͔͉̼̺̬̝̣̲͉̞̼͚͔̱͖̗̹̭͚͎̮͚̖̯̼̠̂ͫ͝ͅͅs̶̨̤̬̹̰̹͓͖͕̣̺͖̝̖̱̪͉̳̮͍̟̤̹̟̦̦͓̼͉̲̘̘̼̤̞͙̟͎̜̪̫̖͈̩̹̙̘̲̻̜͈̖̟̞̞̙̩͚͇͉̤̎ͪ͂ͦͭ̚͟͜͞ͅͅͅt̑̃ͨ̑ͫ̓͆̇̓̃̇̑ͭ̇ͦ ҉̛̛͔̲̭̖͙̪͚̱̲̞̞̮̫̬̠͕̖̻͖͚̘̹̱̹̰̯̦̻͎̭̳̦͚̙͚̕͘įͧ̓ͧͣͤ͊ͬ͛̀̿ ҉̧̛̼̙̜̞̻͕̼̠̳̹͔͙͎͚̜̱̰͕̭̜̤̪̞͉̮̱͓̬͇̙̘̟̤͇̹̻͎̲͙̫ͅṉ̷̷̢̰̮͓͙͓͉̩̜̹͎̺͇̯̯̦̹̪̝͍͍̟̯͇͕̝̳̠͇̲̟̪̜͔͎̘͚̹̬̦̻̙̫̯̰͔̳̰̞͇̦̥̰̲̱̂̉̈̅ͭ͗͊͡ͅg̵̨̧̞̬̭̪̖̣̺̝̪̝̠̞̤̼͕̖͖͚̯͉̜̭̩͖̩͍͙͎̜̙̤̜̺̱̹̼̗͔͔̞̮̊̑̊ͯ̋͗͋ͩ̄ͦ̑̃̌ͧ͋́̆̕͞ͅͅͅ ̢̛̯̳̹͔̺͉̟͈̠̠̯̙̜̗̗͔̜͍͕̩̳͙͔͎̘̭̩̥̫̩̠̩̺̬̣̙̦̠̦̻̯̬̖̻̠͈̙̭̫͖͈́̌̂ͣ͂͐̊͑ͅt̴̢̧̹̥̻̭̞̼̱͖̯̟̘͈͙̻̘̦͎̳̫͖̜̋̿̈̇ͬ̽̀͡e̸̷͍͈̫̭̬̜͙͔͔͖̹̹̯͈̗̹͓̗̗̟̯̦̮͚̖͎̮̠̮̩̫̯͖͖̬ͥͨ͊̾̾̒̀̉̾̌͐̈͛͂̆̅̏ͣ͢͝͠ͅͅs̸͖͇̥̫̼͕̭̻̤̤͈͇̱͎̫͇̜̣̬̖̦̥͈͇̝͈̹͔̥͙̮͉͙̮̾́̅̏ͧ̓ͮ̔̒͆̅̍̃̃ͮͥ̚͢͞t̛͈̣͖͎̹͍̜̹̪̘̦͕͎̥̞̪͔̜̤̭̻̪͙̘̯͈̬̖̱̝̖͔̭̰̬̤̫̭̝̞̺̙͈͇̫̥̱̼̲̭̼̾͒̈̔̈͑ͩ͢ͅi̸̧̙̩̺̳̗͖̹͎̳̲̼͙͓̹̗̞̮͎̦̖͓͚̞̮͍̠̲̭͖̩̟̪̺̙̦͖̙̬̜͙͓̠̬̙̝͍̮̙̪͉̬͔̦̖̻͓̻̺̓̄́͛̿͟͢͞ͅͅͅn̸̡͔͎̫̖̤̫̟̬̞̪̬̥̼̞̦̜̗̖͊͆͛̈̽ͩͩ̾̓ͯ̇̓ͦg̸̷̴̡͔̥̱͎͕̖̘̬̪̪͇̱͈̪͈͎̫̗̟̼̠͚̗͓̫̪̺̞̦̝̪̗͎͎̩̩̜̺̫̦͍͚͔̹͕͇̪͔̬̲̥̘̤̗̋͆̊ͭ͋̿͋͋͑͒ͯͤ̾͂̚͝ͅͅ ͉̱̤͔̭͎̰̥͚͎̯̗̤̘̯̩̱̱̝͖̮͍͍̻̬̱̯̬̤̟̬̣͇̯͔͈͇̬̥̱̜̜͔͛̌̽ͯͩ̀͟͝ͅẗ̨̧͉͈̥͉͇̱̫̦̻̪̮̦͙̝̝̣̪͙͖̠̰̟̫̼̹̺̱̩̏ͨͨ͒̽̾ͩ͑̏̎̊̈̌̌̀̚͢ͅͅe̮̩̻̙̺̩̻͒̄́ͦ̾̓̈̏͑̒̆ͭͫ̂̄̍ͦ͢͟͟s̨̡͖͍̯̮͙̼̯̝̖̤̭̗̻̹̠̝̫̯̩̝̬̪̩͇͎̤̝̖̠̠̤̠͍̟̤̙̦̜̭̙̘̼̜̗͍͓̭͎̤̙͉̫̑͛̀̿̃̔ͬ̓͒̇t̵̵͔̞̮͓̹͔̰͍͕͓͕̻͇̥̘̖̮͈͉̮̤̬̞̞̰͉̝̳̗̝̖̣̯̩͚̠̲̼̟͎̣̻͔͙͖̠͉͈̫̱͖ͩͧͤ̈̇̽ͮ̉̃̏̏͆̚̕͝ͅͅi̸̵͙͍͇̩̫̞͔̰̩̜̺͈̣̤̭̻̖̞̲̰̟͖̤̮̲͖̜̳̣̮̖̝̺͚̻̲̪̜̱͍̥̭̦͇̺̫͓̞̮ͮ͛ͣ͒ͤ̀̂͒ͬ̈̄̀̀͜ͅͅn̴͚̞͈̜͓̱̼͇͍̟̺͙͖̮̠̟̤͈̮̣̟͈͚̘͔̘̯̖̬̰̮̮̖͓̰̩̪̖͔̩̪̉̽̄ͣ͌̑͊̑͟ġ̴̺̱͚͖̦̙͚͓̻͇͎̼͓̮̘̟̣̬̫͎͖̫͇͓̬̬͎̞͕̺̫̒ͬͧ̀̓͛̇̄̀ ̢̢̩͍̟͖̭̦̥̪͉͖̟̖͈̼̣͙̦͇̫̜͔͕̬̫̭̠̫͎͉̜̱̯͎̬̖̹̞̻̹̜̹͙̼̦̲̫̹̺͖̭̣̲̓ͣ̍̐̀ͪ̆̕͞t̝̲̹͕̗̫̪͚̟̰͖̝̮͙͖̯͕̖̺̬͔̥̗͚͔̗̺̱̩̹͂̓͋ͫͦͦ̆̊́͜͞ͅe̶̼̹̞̣̩̗̣͈̲̱̹̥͉̬̖̩͈̺͖̱̱̫͈͉̗̪͎̮̟͎̹̦̜̱͉͚̮͉̥͔̥̩͊ͮ̏̃̆̐̈ͭ̊̌͐́́͠ͅͅsͨ̇̈͗̃̑ ҉̣̦̥̻̦̯͉̣̟̮͕̥̖̝̞̙̠̰̗̖̺̠̘̬̙̜͕̬̱̠̤̖̹̦̫̟͓̗͈̝͉͈̬͕̙̗̜̖̥̗̞̬͈͈͍͍̙̬͢͟͡͡ͅͅͅͅṯ̷̶̸̸̤͎̱͖͍̮̰̻̰̤̗̣̠͔̘͇̞͚̪̮̮̙̻̯̮͖̳̰̤͇̭͕̟͈̙̪̗͔̭̝̱͈̫͓͔̯̖̭͚̣̞̫̪͔̟̙͙̱̟̆͐ͩͫ̋̿̓̃ͦͣ̀̅͝ͅi̵̴̱͙̦̼̘̳̼̎͂ͥ͒̋ͅn̡̜͈̞̬͎̺͉̫̝̞̼̥̗̭̖̼͇̮̘̘͔̠̭͉͕͉͕͕̥͔͙̤̙̬̪͕̾̊̎̐͜ͅͅͅͅg̸̡̢̮̭̖̗͔̜͔͍͍̮̺͎͉͙̲̮͍̞̖͓̟̰͙̜͖̝͍̙̗͉̮͔̤̫̩̼̈ͯ̅̾̄ͮ̕ͅͅ
2022-01-09T06:12:14.3286363Z t̢̛̖̙̩͓̱͉͇̜̱̻̬̟̠̙̗͕̬͎̟̜̠͙̳͈̪̗̻̣͖͖̟̪̤͔̬̥̝̥͈ͭ͐͒͐͐ͥͤ͒ͤ͛͡ͅe̢͈̼͇͇͈̦̭̺͎̩̯͉̼̘̺͖̟̩͔͖͖̞̠͍͎̤̖̮̥͈͈̥̫̳͔̯̹̲̔ͮ͋̔̾͛̒̑̾ͨ̿ͩ̓̚͞͡ͅs̷͍̠̪̥̟̗͈̠̪͖̦̙̯̟̼̩͍͔͔̠̳̰̮̦̲͖͉̬̣̺͎̖̫̫͔̬͇̳̫̪̜̲̫̘͚̭̖̦̜͈͗̃ͮ̉ͣͯ̀͠ͅt̶̛̉̑̎͗͊̓͗͆̊̃ͤ̊ͯͭ̊͌̑̽̓͝ ҉͙̥͈͖̤͇̝̻͖͈͙̗̦̰̗͍̙̹̦̺̜̫͍̤̠͉̥̟͉̘̫͖̭͍̞̮͍̥̲͈͈̖̤̤̝͈͝ͅͅi̡̬͚̹̜͇͎̭̦̳͉̦̥̰̳̭̣̥̰̙̞͙̦ͫ̅̒̎́̐͗͛̿́̈͠ņ̴̯̼̺̯̝̬͇̹̺̖̗̤̘̩̻̩̺̥̖̪͍̮͇͙͓̞̦̞̝̼̰͈̫̼͈̻͍̠͙̭̺̣̠̝͍͕̰̬͗͐ͭ̉̔̏ͯ̂ͅͅg̵̢̨̱̬͖͉̱̣͇͖̹̮̱̜͉̟̖͎͓͎̥͍͔̹̱̥͈̜͔͉̮̞̮͚̲͉̥̲̰͎͈̓͊̽́̊͑̇́͑ͨͣ͛̉͊̃̿̏̓͡͝ͅͅ ̴̢͇̲̮̙͓͎̪̖̩̩̣͎̯̠͇̳̞̪̬̬̣̯͚̟̦̔̏̎̓͘͠t̷̴̛̛̗͕̹͇̼͎̲̰̗͕͎̓̓͋̓̉̍ͩ͜e̢̳̩̯͍͈̗͔̺͖̼͓͍̤͕̖͓̭̺͓̗͈̠̲̲̼̮̫͓̖̭̘͎̞͉̪̥̩͉̟̻̮̯̳͍̞̱̪̞̦̤̮͊ͣ̓̽̓̽͑́̌̎ͥ̋ͭͦ̏ͯ͂̚͘͟ͅs̵̸̛͖͇̭͇̟̹͇̪͉̪͍̮͖̪̭̻̖̪̝͓̱̹̬͖͕͉͈̭͉͖͕̩͚̺̫͙͇̣̰̞͍ͦ̏͗̾͛͐̿ͥ̄̉͂̕t̶̬͎͇̰͕͍͔͎̄̒͌̇ͥ͊̏ͬ͝i̢̗̬̩̖̜͓̮̞̪̰̻̗̻͕͎̲̖̭̼̤̗̰͔̜͉͎̝͎͙̭̜̫̪̹͓̻̖̩̟̤͍͕͇̥͚̟̼͙̜͔̟̥̬͇̙̗͖̺̖̩̬ͪͫͦ͆ͭ̐͐͆̓͌̉̈͂̒̄͗́̚͘ͅͅn̴̖̪̳̹̝̙̮̖̘͕̉̑͗̂ͮͭ̉̓͑̋̔̚͠ͅͅģ̵̷͉͎̰͓̠̟̅͐̀ͯ̇ͨ̔͒̋̉̏̔̒̃̽̉̈̎͢͞ ̸̧͔͈̤͙̱̲̰͈̜͚̩̤̬͇̩̟͇̯̮͚͉̜̺͙͖̙̙̳̱̭̰̗̰̭͈͇̺͎̭̖̖̝̼̠̙͙̪̝̲͕̝̮̮͔͓̺̞̳͈͔̓̓̋̍ͣ̉ͫ͝ţ̸̶̠̱͕̫̫͈͈̘̙͔̜̋̎̓ͤ͑͂ͤͩ̚͜ȩ̡̺̟̭͙̝͓͔̜͍̦̯͇̲͓̺̹̯̺͓̥̝̪̘͔͉̖̪̳̦̤̪̠͈̲̘̣͔̱̱͍̟̫̹̣̠̗͙̪̩̘͖͓͓̣ͧ͐ͩ̔̀́̊͛̐͛ͭ͛̓̓͛̐͊͘͘ͅs͗̔ͩ͗ͭͫ͊͗ͬ̑ͮ ҉̻͖̘̼͖̙̼̠̳̦̺͍̩͕̱͈̞̭͖̖͓̞͔̼͚͉͔̫̬̼̮̤̗̠̻̱̯̤͡t̷̋͑͌͌͋̍̆͌̋ͭ̉̾͟͝ ҉̷͍̺̪̱̻͙̺̹̝̦̦̮̳͓̲̪͉̟ͅi̸̧̟͇̙̜͙͈̹̼̗̤̰̫͖̞̫̟͚̜̺̙̫͇͙͖̰͖̗͙͆̈ͤͮͪ̏̍ͥ̓͒̂n̨̡̬̪̮͇̠̥̤͈̩͉̙̞̟͔̞̞͕̬̤̖̱̯̘͓̼̹̟̥̖̦̖̰̺̗ͩ̿͛̒ͮ͌̚͘͡g̵̪̠̖͕̻͍͖̣͔̺̣̟̙̬͕͎̩̗̦͔̩̞̜̜̬͙̭̼̞̰̗̪̘͙͇͔̤̗̰̮͉̩͚͋ͯ̓̽͛ͧͯͬͭ̇͗ͨ̃́͗̄ͧ̓̀̚ͅ ̡̧̺͔̯͎̟̼͖͕̘̯͉̤̤͍̘̖̝͓̰̬̳͕̜̯͍̩̟͈̯̻̰̖̥͙̗̭̤̞̰̤͍̣̖̻̠̟̻̖̼͇͚͖̲͖̤̟̝̦̏̾͐ͣ̎̍͑̓̐ͤ̅̐̎ͮͯ̒̎͜ͅẗ̴̡͓̭̯̳̗͎̮̰̟̭̫̠͚͎̱̣̟̫̩̥̲̣̩̟͎͙̤̮͇̣̠̪̭̟͔̤̱͔̖͕̙̺̗̰͇͔͍̪̞̤̝̪͖̪̠͎͕̼̼̫͙̺̟̫͉̜ͣ̌̽͆̅͟͡e̛̲̮͕̻̮͓̫̲̘̦̪̪̙̪͍̦̣͍̩͍͎̘̞͓̬͔͈̙͙̟͙̥͖͖͎̙̪̼͓̤̳̪̝͔̥̦̳͈̙͇͇͋̇̋̐̓̓̒̈͐͛̅̐͊̋͛̽̏̅̋̕͝ͅͅͅs̴͙̖̱̟͚͇̟̯͈̜̳̠̱̯̠͔̙͍̠͈͈͙̞̜͚̺̞̜̼̜̞̤̜̹͙̬̮̟̼̳̹̠͓̪̜̙̺̪͕̩̗͎̼̹̹͖̩̭̲̠̖̘ͣ͒ͨ̽̎̃ͧͩͩ͜͞ͅͅt̵͖̩̱̣̠̹̠̝̗̹̟̙̦̭͖͔͍̠̺̩͈̥͆ͪ͌ͯ̔͜͝ͅi̡̩͖̤̠͇̱͍̬̪̼͈͎͓͕̫̬͔̰̞̤̖̼͔̘͑̐ͥ͊̃ͯ̊ͦͥͨ̂ͫ͑̎̈̿͌̀ñ̷̨͍̬̫͖̝̙̘̤͎̫͙̙̙͎̺͍̓ͬ̃̋̐̏ͥͪͮ̀͠͠ͅg͇̟̱̭̟̳̞̙̻̪̞̪̝̘̟̝̼͕̝̮̹ͮ͒ͮ̑ͧ̈̔ͨ̿͢͠͝͠͝ͅ ̨͇͉̺͉̺̙̰̗̦͇̠̺̘̗̱͎͉̳̱̥̰̙͙̣̤̫͖̞̭͇͇͍̗͎̦̋̑̍͋͛ͬ̑̓ͪͤ̔̐͘ͅţ̶̛̜̻͇͔̞͓̰͙͍̞̰͍̩̬̮̗̟͓̖̪̼̯͚̼͔̭̲͈̪̱̺̹̭̰̹͇̬͓͔͈̝͚͓̼̰̰̮̹̝͚͉̀̈͂̌ͫ̅̇͆͗̌̔̆̓͢͡ͅͅͅȩ̛͇̯̣̫͉̣̬͕͎̭̜̹̝͍͈̖̰̗̦̻̳̹̩̝̼̬͇̹̝̻̗̤̘̤̦͙̯̙̭̘̰̤̗͍̫͔̘̣̱̭̩͉̠̭͖̲̯̪͈ͧͨ͆̂ͧͨͨͧ̀͐̌̊͊ͨ̃ͮ̑ͤ̚ͅͅͅs̵̡͔̫̗̖͈̼̦̼̞͈̙̠̻̞̳͈̜͍̭͉̰̃̀ͪ̒͗ͧ͢ͅẗ̷̷̟͖̻͙̼̠͔̝͈͑͊ͯ̽ͩͬͨ̃̅̒̀͢͟iͨ̎̋̆̆̆͛ͮ̊̾ͫͥ̏̑͂ͮ́ ҉̡̢̤͖̮̯̬͎̦̻͖̭͎̖͉̗̦̣͎̙̭̦͉̟̦͉͇̠̺͈͔̱̹͟͠ņ̛̥̥̭̪̠͉͔͔̤̲̰͇͙̗͎̜͖̜̠͈͇͉̝̹̻̖̰̱͉̪͈͕̲͙̥̻̟̹̳͍̹̜̯͕͇͙̰̳͙̰̰͈̥̭̲͈͙̫̲̰̣̟͕̋ͧ̈ͬ̐̔͢ͅͅg͚̗̝̻̞̲̩͕̩̮͙̯͕̰̤̖͔͉̤̺͈̭̹̰͖͕̳̰̦̘͓͍̙͗̍ͤ̽́ͯͧ͜͠ͅ ̟͇̥͕͉̤͈͔̤̫̫͚̦̞̥̜̘̜͍̘͚̯̥͉͉̼̫̙̗͍̲̝̠̗͚̮ͨ̽ͤ͑́͟͞ͅͅͅt̡̩̮̳͈͍̬̤̗̘̫̩͎̹̬̩͕̯̹͈̫̣̞̠̮̲͔̞̩͖̞͎̭̮̳̻̪̰̝͉̟̠̥̫͔̳̟̝̪̼̖͈̜̟͍͓̺̳̖̺̝͕ͩ͑̊̋͌̄̅ͬ̓͛͑ͣ̓̉̅̇͆ͬ̎́͢͜͠e̡̙͙͚̣̻͍̞̻͕̥̝̞̗̥̞̪͍̦͆̍̈́̃͌ͤ̓ͯ̈̊̆̌ͤ̓͞s̷̶̠̯͚̼̦̣̹̥̙͔̤̻͙̜̙͖͖̪͕̭̙͇͉̣̭͈̥͍̘̪̦̦̣̭̬̝̼̳͙͔̈̾̅̊̇ͧͨͫ̽̋̕͢͞ͅͅt̨ͣ̓ͤ͆ͦ̇ͧ͋̈͌ͧ́̚ ҉̫̬͕̖̤͉͖̠̲̗͎͘͝į̧̛̣̖̞̮͉͉̲͓̜̫͒̑ͫ̍̇ͫ̐ͩ̎̍̽͐ͣͪ̍̋͛́͟ͅͅn̨ͫͨͭ̋̌̅̈̇͒ͣͩͩ̉ͯ͗ͨ̽ͭ̚͘ ҉͖͈̤̙̲͖̗̞̹̫̜̣͉̤̲̙̠̱̬͕͈̝͓͖͖͚͓͓͈̱̪̫̜̰̯͖͍̰̹̼̹͓̺̖͚̩̘̰̳̮̠͚̠̦͕̩͓̯̮̟̣̘̦̫̝͔̥g̛̈ͤͨ̽ͥ͊ͣ̿ͦ̈͒͆̅͟ ҉̨͈̼̠̻͇̯̭̻̺̫̘̜̯̜̺̫̙̤͓̦̪̞͖̭̙͚͓͖͍͙̰̫̯̘͙͖̣̻̟̮̲̳̤̤͉̯̮͙̰̭̬̥̘̳͖̪̦̞̬̫͈̮͇ͅͅͅ ̸̷̨͓͈͇͔̱̺̲̬̭̪̥̦͉̗͚̻̭͕̬̪̰̮̣̭̱̮̳͎͙̠̥̝͇̻͉̞͍̼̫̼̥̜̼͈̼̮̰͙͉̪͍̎͌͛̓͛̌̀ţ̳͕̙̯̳͎̹̹̪̼̯̣͚̠͕͓͓̫̙̤̥̈͑͐ͧ̂ͬ̊̉̏̚͜é̸̖̫̲͙͎̭̹͔̩̜͍̱̩͍̼̣͓̦̰̳̥̱̝̮̞͍͚̰̳͖̳̘̮͇̬̜̥̱̜̯̰̝͎̱͎͈͖̻̥̪̰̯̥̖̳̘̫̲͕͇̺̮̏̓̀ͦ͒ͥ̌͒͘͝ͅͅͅs̵̡̳̲̣̟͕̤͇̺̘͔̩͇̱̪̮̰̝̮̪̫̼̰̬͔̩̬͖̗̤͇̪̜̫̝̥̞͕̤͈̗̣͓̽ͨ̈ͥ̉̑̇̉̚͞ͅt̸̢̜̮̰͎̰̪͎̞̾ͥͩͬ̈̑̆ͭ͑ͬ̍͜͟͢ͅͅi̸̧̧͉̗͇̭͇̞͈̜̠̼̦͚͕̖̥͙͖̰̠͚͓̠̟̥̬̻̥̝̬̜͓̲͎̙̪ͤ͒ͯͪͨ͊͌̓̓͟͡ͅn̛̪͈͉͔̪̣̮̞̣͎̘̫̹̙͚̘͖͕̹͚̺̥̤͔̭͎̭͙͈̱͉͈̯̲̺̠̟̭͎̮̲͎̣̺̳̻͓̯̭͈͓͇ͫ̏͌̓ͯ̀̚͜͞͝g̵̡̫̦̞̥̙̼͚̲̰̱͈͔̹̤̬̜͈̜̜̮̺̣͖̣̘̹͚̗̃ͩ̑ͧ͋͑ͭ͐̈̋̌̐̋̀͗̏̚̕͘
```
See full logs below

**To Reproduce**

1. Run `yarn global add netlify-cli`

**CLI Output**

Run failure for github action https://github.com/mrloop/activity-merge/actions/runs/1673191915 see logs

[3_Install netlify-cli.txt](https://github.com/netlify/cli/files/7834845/3_Install.netlify-cli.txt)

**Comment by sawa-zen** [comment] 2022-01-09 11:44
It seems to be caused by the author of colors.js adding infinite loop processing to the release.
https://github.com/Marak/colors.js/commit/074a0f8ed0c31c35d13d28632bd8a049ff136fb6

**Comment by erezrokah** [comment] 2022-01-09 20:25
As a workaround please use `npm install -g netlify-cli`. We publish a shrinkfile file with the CLI that prevents such issues by locking the CLI dependencies during publish time, however `yarn` doesn't support it, hence it takes the latest (and broken) version of `colors.js`.

**Comment by SamusElderg** [comment] 2022-01-10 08:03
For those using GitHub actions like: `uses: netlify/actions/cli@master` in their `.yaml` file in their `.github/workflows` folder, I have forked and flipped it to `npm` instead as a temporary fix you can change your workflow file to something like this:

```
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: 🧰 Install Dependencies
        run: yarn install
      - name: 📦 Build Project
        run: yarn build
      - name: 🧹 Run Lint
        run: yarn lint
      - name: 🐛 Run Tests
        run: yarn test
      - name: 🚀 Deploy to Netlify
        uses: SamusElderg/actions/cli@master
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        with:
          args: deploy --dir=build --prod
          secrets: '["NETLIFY_AUTH_TOKEN", "NETLIFY_SITE_ID"]'
```

Simply swapped over the Netlify deploy setup action from:
`uses: netlify/actions/cli@master`
to:
`uses: SamusElderg/actions/cli@master`

Where this forked repo's action uses:
`RUN npm install --unsafe-perm=true -g netlify-cli`
instead of: 
`RUN yarn global add netlify-cli`

Don't do this change blindly, don't trust; verify: https://github.com/SamusElderg/actions/blob/master/cli/Dockerfile

And ideally, just fork it and point to your own fork instead of blindly pointing to my repo, (or better yet, add the RUN command directly in your CI instead of using an action), it's only small, that way you don't have to trust that I won't change/break it in my repo

**Comment by erezrokah** [comment] 2022-01-10 11:18
Re-opening as the fix didn't work

**Comment by erezrokah** [comment] 2022-01-10 11:46
Looks we need to wait for https://github.com/rafeca/prettyjson/pull/54#issuecomment-1008784779 as it was fixed in https://github.com/npkgz/cli-progress/issues/116#issuecomment-1008272485 and https://github.com/winstonjs/logform/pull/128

**Comment by XhmikosR** [comment] 2022-01-11 10:23
npm removed the offending colors versions so this should no longer happen.

**Comment by erezrokah** [comment] 2022-01-11 13:49
Closing as solved

**Closed by erezrokah** 2022-01-11 13:49 UTC
Labels: type: bug
