### ISSUE TITLE
How can we improve deploy times

### ISSUE THREAD

**Issue by amuttsch** [netlify/cli#1838] opened 2021-02-03 15:06 UTC
**Is your feature request related to a problem? Please describe.**

We have a next.js application with around 30 server side rendered pages, which result in a function for each one. The deployment of this site takes around 6-9 minutes on our CI runners and around 4 minutes on my local machine. This is a big chunk of our total pipeline runtime. From what I see most of the time is spent on hashing and building the function zip files using [zip-it-and-ship-it](https://github.com/netlify/zip-it-and-ship-it). This is done single threaded as far as I can see (as it's a JS library). Our route js files are around 5MB in size each.

We use `next-on-netlify` to prepare our build and `yarn run netlify deploy` to deploy it to netlify.

We already reduced the number of SSR pages which significantly sped up the build time, but we cannot further reduce it.

Maybe enabling the concurrent generation of zips using worker threads might be an option to utilize multi core runners (should I create an issue in zip-it-and-ship-it for this?).

Are there any options we can use to speed up the generation of the zips and hashes? Do you have further suggestions how we can set up our pipeline / deployment to get faster deployments? Thanks!

**Describe the solution you'd like**

A faster deployment :-)

**Describe alternatives you've considered**

:heavy_check_mark: Reduce the amount of pages in our application.

**Can you submit a pull request?**

No, not for `cli` per se. Maybe a draft in zip it and ship it using worker threads.

**Comment by eduardoboucas** [comment] 2021-02-04 11:56
Hi @amuttsch. We're working on some improvements to our bundling mechanism as we speak, which hopefully will bring some performance improvements. In fact, I would LOVE to see how the work we're doing will affect your build times specifically. Would you be open to trying it out while it's still in an experimental phase and sharing your results with us? Thanks!

**Comment by amuttsch** [comment] 2021-02-04 13:26
Hey @eduardoboucas Thanks for your response :-) Yes, we can try the improvements on our builds, I'm happy I can to help improving the bundle times :+1: 

How do we proceed? Is there an experimental version available I can build and test against?

**Comment by eduardoboucas** [comment] 2021-02-04 13:47
Awesome! We still have some things that we need to set up on our side. Once that's in place, I'll drop you a note with instructions on how to proceed.

Thanks!

**Comment by amuttsch** [comment] 2021-02-04 14:25
Perfect, thanks!

**Comment by amuttsch** [comment] 2021-02-04 15:11
I did a profiling run on `zip-it-and-ship-it` and it turns out it is not the zipping that is slow, but in fact the parsing of the function code as you can see here. The main culprits are `babel` on the blue stack and `node-source-walk` on the right hand:

![image](https://user-images.githubusercontent.com/5488288/106912533-66ab5780-6703-11eb-9771-29fbd36a7a7f.png)

Combining it with the amount of functions we deploy the complete profile looks like this:

![image](https://user-images.githubusercontent.com/5488288/106912632-7a56be00-6703-11eb-8473-606025cc1501.png)

The zipping takes around 30ms, which is totally negligible.

**Comment by amuttsch** [comment] 2021-02-04 15:36
Is the function parsing for validation purposes only or does it provide necessary data for the deployment? If it's just validation a possible solution would be to add a flag to skip this step. 

For our code the `next build` produces proper function code which (I think) guarantees a valid function code, so I think we could skip such a validation in this case.

**Comment by eduardoboucas** [comment] 2021-02-09 21:13
Hi @amuttsch! Can you please try to run a build with the following environment variables:

```
NETLIFY_EXPERIMENTAL_ESBUILD=true
NETLIFY_EXPERIMENTAL_EXTERNAL_MODULES=critters,nanoid
```

You can add them in the UI like you do with any other environment variables.

The first variable is setting esbuild as the bundling mechanism, whereas the second one is flagging two modules as external (since Next.js does not declare them as dependencies).

If you could try running a couple of builds and share your results and any issues you run into, that would be super useful.

Thanks!

**Comment by amuttsch** [comment] 2021-02-10 08:59
Hi @eduardoboucas, thanks for your reply :-) 

I tried our build with and without the environment variables, but the deploy times are around the same on my machine (~250s). I used the following command: `yarn run netlify deploy -d out_publish -f out_functions --prod`

After checking the environment variables I saw that they are used in the `build` command, but not in the `deploy` one. I updated my `netlify.toml` to have the build command: `yarn run next-on-netlify` and compared the runtime. 

```
yarn run netlify build: 
    build.command completed in 929ms
    Functions bundling completed in 3m 29.4s
NETLIFY_EXPERIMENTAL_ESBUILD=true NETLIFY_EXPERIMENTAL_EXTERNAL_MODULES=critters,nanoid yarn run netlify build: 
    build.command completed in 968ms
    Functions bundling completed in 3m 26.1s
```

Here too are only minor differences well within the margin of error. My assumption is that the changes that the two environment variables only affect the actual application build process, but not the bundling of the functions.

In our case the building of the next.js application using `next build` runs around 2 min, whereas the `netlify deploy` needs 4 min (both on my local machine). 

I think the main issue is that `netlify deploy` assumes we have unbundled js functions and therefore analyses and bundles them. But next.js produces bundled js files which contain all dependencies and thus need only zip packaging and uploading. Can we somehow tell the `deploy` command to *not* bundle the functions but take them as is? I think this should improve our deploy times significantly.

Or am I missing sth. here?

Versions used: 
```
"netlify": "6.1.7",
"netlify-cli": "3.6.0",
"next-on-netlify": "2.8.7",
```

**Comment by eduardoboucas** [comment] 2021-02-10 10:35
Thanks @amuttsch! You're not missing anything, I just realised that the flow you're using (i.e. bundling the functions locally via the `netlify deploy` command) isn't yet covered by this experiment.

Is there any chance you could try to run a build without local bundling? If your site is connected to a Git repository, you can commit the (unbundled) source and hit *Trigger deploy* from the *Deploys* pane in the Netlify UI.

If this is too much hassle, or if it simply doesn't fit your workflow, I'll make the necessary changes on our side to make this work with local bundling.

**Comment by amuttsch** [comment] 2021-02-10 13:38
Unfortunately I'm not able to run a build on netlify directly as we don't have the git repo connected (company decision). So the CLI `deploy` workflow is the option we have to use.

So yes, if you can make changes on your side that the `deploy` command will utilize the improvements as well that would be much appreciated! :-)

**Comment by eduardoboucas** [comment] 2021-02-10 13:40
> So yes, if you can make changes on your side that the deploy command will utilize the improvements as well that would be much appreciated! :-)

Absolutely. I'll circle back once this is in place. Thanks!

**Comment by amuttsch** [comment] 2021-02-10 13:41
Awesome, thanks!

**Comment by eduardoboucas** [comment] 2021-02-11 09:58
Hi again @amuttsch!

Can you please try the following steps:

1. Upgrade the CLI to the latest version

    ```
    npm i -g netlify-cli
    ```

2. Verify that `NETLIFY_EXPERIMENTAL_ESBUILD` and `NETLIFY_EXPERIMENTAL_EXTERNAL_MODULES` are both defined

    ```
    netlify env:list
    ```

3. Build your site and functions

    ```
    netlify build
    ```

4. Verify that you see a warning message related to the experimental feature

    ```
    You've opted in to an experimental bundling mechanism via the "NETLIFY_EXPERIMENTAL_ESBUILD" environment variable.
    We recommend against using this functionality in production sites since its behavior may change or it may be removed 
    entirely.
    For the latest updates about function bundling, please visit our Community forum: community.netlify.com.
    ```

5. Deploy your site using the functions bundled in step 3

    ```
    netlify deploy -f .netlify/functions
    ```

The new bundling mechanism is not fully integrated yet, hence the two-step approach of running the build step and then the deploy. I'm particularly interested in how long it takes for step 3 to complete and whether you see any difference in functionality after you deploy the site in step 5.

Looking forward to hearing from you. Thanks!

**Comment by amuttsch** [comment] 2021-02-12 10:35
Hey @eduardoboucas 

Thanks for the quick update, I really appreciate your fast response :-)

Netlify CLI:

```
netlify-cli/3.7.1 linux-x64 node-v14.15.1
```

Netlify Env List:

```
-> % yarn run netlify env:list                                                       
yarn run v1.22.10
$ node_modules/.bin/netlify env:list
site: some-testing-site
.---------------------------------------------------------.
|                  Environment variables                  |
|---------------------------------------------------------|
|                  Key                  |      Value      |
|---------------------------------------|-----------------|
| NETLIFY_EXPERIMENTAL_EXTERNAL_MODULES | critters,nanoid |
| NETLIFY_EXPERIMENTAL_ESBUILD          | true            |
'---------------------------------------------------------'
Done in 1.61s.
```


Building site:

```
$ yarn run netlify build
...
(Netlify Build completed in 1m 10.6s)
Done in 72.23s
```

WOW, that is amazing!!! The build (clean and `next build`) and bundling took just over a minute! This is a huge improvement for us. The deployment seems to work just fine - of course we have to see if sth. is broken once we test this more thoroughly, but this looks fantastic!

Just as a side note: I also tried used the `@netlify/plugin-nextjs` instead of `next-on-netlify` directly. Both seem to work fine.

However, during the bundling I got a lot of warning messages like those:

```
> node_modules/@ampproject/toolbox-optimizer/lib/DomTransformer.js: warning: This call to "require" will not be bundled because the argument is not a string literal (surround with a try/catch to silence this warning)
    169 │         Transformer = require(`./transformers/${Transformer}.js`);
```

or

```
> out_functions/next_search/nextPage.js: warning: Comparison using the "===" operator here is always false
    106253 │         if (allRoutes === [] || !matchPath) {
```

Thanks again for your quick help and the huge improvement this makes - I'll add this experimental build to our branch pipelines to validate that it's working as expected. If I encounter any issues I'll let you know! :-)

**Comment by eduardoboucas** [comment] 2021-02-12 10:56
Thanks @amuttsch! I really appreciate the feedback.

We'll continue to work on improving the developer experience, which will include offering more information (and ideally automatically resolving) warnings like the ones you're seeing.

I'll keep sharing any updates here. In the meantime, if you do encounter any unexpected behaviour from your tests, please let me know.

Thanks!

**Comment by eduardoboucas** [comment] 2021-02-23 19:24
Hi @amuttsch! Just checking in to ask if you have been using the experimental bundler. If so, did you run into any issues?

Thanks!

**Comment by amuttsch** [comment] 2021-02-24 07:51
Hey @eduardoboucas Yes we are using it daily to drive your branch deployments to netlify. It works without any issues so far. We really enjoy the much faster pipelines :rocket:  Thanks again for your super fast responses and improvements, I really appreciate it :heart:

**Comment by amuttsch** [comment] 2021-03-04 09:25
@eduardoboucas With the PR above the configuration for this flag has changed. Unfortunately, from the PR I cannot see how we can enable the faster bundling now. Can you give me an example how we can archive this?

Thanks! :-)

**Comment by amuttsch** [comment] 2021-03-04 09:45
I think I see what my issue is. I had the `NETLIFY_EXPERIMENTAL_ESBUILD` environment variable set in the `netlify.toml`. Now this variable is evaluated in the `cli` rather than in the `build` which caused the old bundling mechanism to be used.

I added the env var to the global context, now `esbuild` is used. However: I get warnings that my functions bundled with errors and `netlify build` prints all function code to the console, several megabytes of data. This seems like a bug as previously only the actual error with the corresponding line was printed. This breaks the new `esbuild` for us unfortunately as this takes lots of time to print all the data to the console. Can you have a look at this @eduardoboucas ? Thanks! :)

**Comment by eduardoboucas** [comment] 2021-03-04 09:56
Hi @amuttsch! Thanks for the feedback.

You're right. We kept the environment variable, but I now realise that it needs to be used slightly differently. Sorry about that!

As for the warnings, that is strange. We should be printing only the offending line, not the entire function code. Are you minifying the code before it reaches the bundler? And is there a repository that you could share that I can use to reproduce? I understand that you might not be able to share your project, but if you manage to create a sample project where the issue is reproduced, that would really help.

Thanks for your patience!

**Comment by amuttsch** [comment] 2021-03-04 10:14
Sure, here you go: https://github.com/amuttsch/test-esbuild-netlify

You can build with `yarn netlify:build`, you should see the console output that is printed. Let me know if you need more information. And thanks for your super fast response :)

**Comment by eduardoboucas** [comment] 2021-03-04 11:02
Thanks @amuttsch! I was able to reproduce the issue. I'll let you know as soon as I have a fix.

**Comment by eduardoboucas** [comment] 2021-03-04 21:15
@amuttsch this should be fixed in the latest release (v3.10.6). Please let me know if you still encounter any issues. Thanks!

**Comment by amuttsch** [comment] 2021-03-05 15:11
@eduardoboucas Thanks for the quick fix, you are super fast :rocket: I'll have a look at it on monday and get back to you :)

**Comment by amuttsch** [comment] 2021-03-08 12:36
@eduardoboucas I enabled the esbuild again and our bundle times are down again. The logs look good as well, thank you so much! :-) :rocket:

**Comment by eduardoboucas** [comment] 2021-03-19 11:29
Hi! In the latest release (v3.13.4), we've deprecated the `NETLIFY_EXPERIMENTAL_ESBUILD` environment variable in favour of a new `functions` configuration block in `netlify.toml`. To enable esbuild, add the following to your configuration file:

```toml
[functions]
  node_bundler = "esbuild"
```

I don't expect any new changes after this. We'll be adding documentation for this new configuration property next week.

Thanks for your patience and help! If you encounter any issues, please let me know. 🚀 

(cc @amuttsch)

**Comment by amuttsch** [comment] 2021-03-22 09:54
Thanks @eduardoboucas 

The new configuration works for us :-)

**Comment by SimeonUnder2** [comment] 2021-03-29 09:22
This just cut our builds from ~12 minutes to ~3 🎉 

(We're seeing the same errors about `This call to "require" will not be bundled...` as reported above, but the built site still works)

**Comment by eduardoboucas** [comment] 2021-03-29 09:25
> This just cut our builds from ~12 minutes to ~3 🎉
> 
> (We're seeing the same errors about `This call to "require" will not be bundled...` as reported above, but the built site still works)

Wow, that's a pretty dramatic change! Can you share some details about your setup, like any framework you're using and a rough number of pages/functions? Many thanks!

**Comment by SimeonUnder2** [comment] 2021-03-29 13:53
Sanity/Next.js, 1135 pages (currently).

**Comment by erezrokah** [comment] 2021-08-11 15:58
Looks like we can close this issue. If I'm mistaken please comment and I'll re-open.

Thanks everyone for the information and @eduardoboucas for being on top of this 🚀

**Closed by erezrokah** 2021-08-11 15:58 UTC
Labels: type: feature, area: functions, area: command: deploy, init/es-func-bundle
