### ISSUE TITLE
Bug(deps): deprecated dependencies when installing Netlify CLI

### ISSUE THREAD

**Issue by erezrokah** [netlify/cli#1528] opened 2020-11-05 12:09 UTC
**Describe the bug**

Installing the CLI produces `deprecated` warnings.

**To Reproduce**

1. Run `npm install -g netlify-cli`

See the following warnings:

```
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated object-keys@0.2.0: Please update to the latest object-keys
```

**Configuration**

```bash
  System:
    OS: macOS 10.15.7
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 58.40 MB / 32.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 14.9.0 - /usr/local/bin/node
    Yarn: 1.22.5 - /usr/local/bin/yarn
    npm: 6.14.8 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  npmGlobalPackages:
    netlify-cli: 2.67.4
```

**Expected behavior**

No warnings should be printed

**Comment by ehmicky** [comment] 2020-11-05 13:16
Some additional information. For `object-keys@0.2.0`, this is the reason:

```
@netlify/plugin-edge-handlers@1.9.0
│ └─┬ rollup-plugin-node-builtins@2.1.2
│   └─┬ browserify-fs@1.0.0
│     ├─┬ level-filesystem@1.2.0
│     │ └─┬ level-sublevel@5.2.3
│     │   └─┬ xtend@2.0.6
│     │     └── object-keys@0.2.0 
```

For `urix@0.1.0` and `resolve-url@0.2.1`, this is the reason:

```
copy-template-dir@1.4.0
  └─┬ readdirp@2.2.1
    └─┬ micromatch@3.1.10
      └─┬ snapdragon@0.8.2
        └─┬ source-map-resolve@0.5.3
          └── resolve-url@0.2.1
          └── urix@0.1.0
```

**Comment by simplenotsimpler** [comment] 2021-08-13 21:10
npm install netlify-cli --save-dev

Still an issue with version 6.3.5:

npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated rollup-plugin-inject@3.0.2: This package has been deprecated and is no longer maintained. Please use @rollup/plugin-inject.
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.

**Comment by erezrokah** [comment] 2021-08-16 09:15
I believe [this](https://github.com/netlify/cli/issues/1528#issuecomment-898721991) is coming from our Edge Handlers plugin and should be solved by https://github.com/netlify/netlify-plugin-edge-handlers/pull/456

**Comment by sarahetter** [comment] 2023-09-14 20:54
Closing as dupe of https://github.com/netlify/cli/issues/1528 (which has more details now)

**Closed by sarahetter** 2023-09-14 20:54 UTC
Labels: good first issue, type: bug
