### ISSUE TITLE
Wrongfully modifies .gitignore

### ISSUE THREAD

**Issue by XhmikosR** [netlify/cli#506] opened 2019-09-03 14:45 UTC
I already have this in my .gitignore file

```
/.netlify/
```

yet when I link the site the first time, netlify-cli modifies my .gitignore and adds this:

```

# Local Netlify folder
.netlify
```

It shouldn't modify .gitignore in this case.

Using `netlify-cli/2.13.1 win32-x64 node-v12.9.1`

**Comment by DavidWells** [comment] 2019-09-03 15:05
Thanks for the report. 

Looks like we are looking for `.netlify` here https://github.com/netlify/cli/blob/master/src/utils/gitignore.js#L91

`./netlify` is an unknown pattern we can add that to the check

**Comment by XhmikosR** [comment] 2019-09-03 15:08
Yeah, I guess you should use a regex there.

**Comment by sw-yx** [comment] 2019-09-03 21:37
i would also prefer to be asked before any file system changes are made tbh

**Comment by DavidWells** [comment] 2019-09-16 18:33
`/.netlify/` will only ignore root `.netlify` folder.

`.netlify` will ignore it in parent & in children.

The `.netlify` folder shouldn't ever be committed into git history as it could contain sensitive information.

Adding `.netlify` even if `/.netlify/` exists, is the intended behavior 

Closing this for now.

**Closed by DavidWells** 2019-09-16 18:33 UTC

**Comment by XhmikosR** [comment] 2019-09-16 18:35
That's just wrong. You are assuming everyone has sub projects. That's not
how git ignores work. And I'd rather be strict with my ignores.

**Comment by XhmikosR** [comment] 2019-09-16 18:37
And also, why on earth would a tool modify a file that doesn't belong to it
in the first place? That's just nasty.

**Comment by DavidWells** [comment] 2019-09-16 19:18
I hear you @XhmikosR. 

We need to protect users who might not understand all the intricacies of how `gitignore` patterns work and stop them from committing files that could contain sensitive information.

This only runs when `netlify init` and `netlify link` are executed. Typically this would happen once per project. You can remove the additional `.gitignore` line and everything should be okay.

**Comment by XhmikosR** [comment] 2019-09-16 19:22
I have literally hundreds of projects I don't have on netlify and I just
want to upload quick previews.

This behavior is very annoying and netlify shouldn't even try to make this
change.

So, either tweak the code to work with a regex or drop this IMO.

**Comment by XhmikosR** [comment] 2019-10-01 22:00
You guys should seriously reconsider this. I can't be the only one.

Just don't modify files that don't belong to you.
