### ISSUE TITLE
[BUG]: Netlify dev --live doesn't work

### ISSUE THREAD

**Issue by kriscard** [netlify/cli#521] opened 2019-09-11 15:23 UTC
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**- Do you want to request a *feature* or report a *bug*?**
Bug

**- What is the current behavior?**
When I launch a live server with `Netlify dev --live` everything seems to work fine but when I go to the Netlify URL nothing is displayed.

**- If the current behavior is a bug, please provide the steps to reproduce.**
1- Launch a Netlify dev --live server
2- Use the generated URL
3- Nothing is displayed
4- Go on localhost:3000 everything works perfectly.

**- What is the expected behavior?**
Get a copy of my local environment and use the generated link to share with other developers. With that, they will be able to see what is in my local environment. 

**- Please mention your node.js, and operating system version.**
Node v12.1.0
Mac OS Mojave 10.14.6
Netlify-cli/2.11.31

![Screenshot 2019-09-11 17 21 17](https://user-images.githubusercontent.com/3465831/64710683-ac390600-d4b8-11e9-9afd-98c12e8503f4.png)
<img width="857" alt="Screenshot 2019-09-11 17 21 48" src="https://user-images.githubusercontent.com/3465831/64710684-ac390600-d4b8-11e9-8bc8-906bb793b8ac.png">

**Comment by raeesbhatti** [comment] 2019-09-11 15:56
Thanks for reporting @kriscard. I've just moved this issue to Netlify CLI repo, since the `netlify-dev-plugin` was merged into the CLI repo.
We're received this reports about this problem from other users as well. We're looking into this, please hold on.

**Comment by kriscard** [comment] 2019-09-16 15:29
Hi, 
Is there any news or advancement on this issue, please? 

Thanks in advance,

**Comment by stephenhowells** [comment] 2019-10-03 20:46
![image](https://user-images.githubusercontent.com/436173/66162715-adef7880-e5e3-11e9-8658-9ce3c66424ba.png)

I'm seeing an issue with `netlify dev --live` as well where the dev server exits with this message:

```txt
FATA[0030] can not connect with server                   error="context deadline exceeded"
```

The Nelify dev server works normally when the live flag is ommitted so this appears to be an issue specific to the live feature.

**Comment by samajammin** [comment] 2019-10-23 20:07
I'm seeing an issue with `netlify dev --live` as well but perhaps for different reasons. When I run that command, it doesn't even output a URL:

```
~/code/ef/ethereum-org-website « git:(netlify-redirects)
$ netlify dev --live
◈ Netlify Dev ◈
◈ Injected build setting env var:  CROWDIN_API_KEY
◈ Starting Netlify Dev with vuepress
Waiting for localhost:8080.
◈ Lambda server is listening on 34567
yarn run v1.17.3
$ vuepress dev docs
.wait Extracting site metadata...
tip Apply local theme at /Users/samrichards/code/ef/ethereum-org-website/docs/.vuepress/theme...
tip Apply theme local ...
tip Apply plugin container (i.e. "vuepress-plugin-container") ...
tip Apply plugin @vuepress/register-components (i.e. "@vuepress/plugin-register-components") ...
tip Apply plugin vuepress-plugin-anonymous-31d57d61 ...
tip Apply plugin @vuepress/active-header-links (i.e. "@vuepress/plugin-active-header-links") ...
tip Apply plugin redirect (i.e. "vuepress-plugin-redirect") ...
tip Apply plugin dehydrate (i.e. "vuepress-plugin-dehydrate") ...

● Client █████████████████████████ building (40%) 204/206 modules 2 active
 cache-loader › vue-loader › cache-loader › vue-loader › markdown-loader › docs/index.md

ℹ ｢wds｣: Project is running at http://0.0.0.0:8080/
ℹ ｢wds｣: webpack output is served from /


● Client █████████████████████████ building (44%) 289/296 modules 7 active
 node_modules/ansi-html/index.js

ℹ ｢wds｣: Project is running at http://0.0.0.0:8080/
ℹ ｢wds｣: webpack output is served from /
ℹ ｢wds｣: Content not from webpack is served from /Users/samrichards/code/ef/ethereum-org-website/docs/.vuepress/public

✔ Client
  Compiled successfully in 3.69s

ℹ ｢wds｣: Project is running at http://0.0.0.0:8080/
ℹ ｢wds｣: webpack output is served from /
ℹ ｢wds｣: Content not from webpack is served from /Users/samrichards/code/ef/ethereum-org-website/docs/.vuepress/public
ℹ ｢wds｣: 404s will fallback to /index.html
success [13:06:30] Build fe410e finished in 3696 ms!
> VuePress dev server listening at http://localhost:8080/

✔ Client
  Compiled successfully in 184.08ms
success [13:06:31] Build eaea51 finished in 185 ms! ( http://localhost:8080/ )
```

**Comment by jackleslie** [comment] 2020-02-06 11:30
I'm getting this same issue @samajammin

**Comment by dimavolo** [comment] 2020-04-20 18:12
Any updates on this? When I run `netlify dev`, I'm getting `error while proxying request: socket hang up` (not randomly, on every call), and I wonder if it's related to this `--live` issue.

(with Vue CLI)

**Comment by erezrokah** [comment] 2021-04-25 10:14
Closing this issue per my comment [here](https://github.com/netlify/cli/issues/719#issuecomment-826297308).
I've tested the new tunnel client on a Next.js site and it works.

If you're still experiencing issues please open a new issue with a reproduction.

**Closed by erezrokah** 2021-04-25 10:14 UTC
Labels: area: command: dev, area: dev-live, type: bug
