### ISSUE TITLE
ESM dependencies in v2 functions in pnpm repo cause crash in dev

### ISSUE THREAD

**Issue by ascorbic** [netlify/cli#6106] opened 2023-10-31 07:22 UTC
### Describe the bug

If a repo uses pnpm and has any ESM dependency used by functions, running `ntl dev` causes the CLI to crash with the following error:

```
NestedError: Cannot read from `/Users/matt/Repos/esm-dep-demo/node_modules/.pnpm/filenamify@6.0.0/node_modules/filename-reserved-regex`: EISDIR: illegal operation on a directory, read
    at Module.createReadStream (file:///Users/matt/.nvm/versions/node/v18.18.2/lib/node_modules/netlify-cli/node_modules/cp-file/fs.js:21:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at copyFileAsync (file:///Users/matt/.nvm/versions/node/v18.18.2/lib/node_modules/netlify-cli/node_modules/cp-file/index.js:11:21)
    at file:///Users/matt/.nvm/versions/node/v18.18.2/lib/node_modules/netlify-cli/node_modules/p-map/index.js:141:20
Caused By: Error: EISDIR: illegal operation on a directory, read

  System:
    OS: macOS 13.4.1
    CPU: (8) arm64 Apple M1
  Binaries:
    Node: 18.18.2 - ~/.nvm/versions/node/v18.18.2/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 9.8.1 - ~/.nvm/versions/node/v18.18.2/bin/npm
  Browsers:
    Chrome: 118.0.5993.117
    Safari: 16.5.1
  npmGlobalPackages:
```

### Steps to reproduce

- Clone the following repo: https://github.com/ascorbic/esm-dep-demo
- Run `pnpm i`
- Run `ntl dev`

### Environment

  System:
    OS: macOS 13.4.1
    CPU: (8) arm64 Apple M1
    Memory: 79.47 MB / 8.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.18.2 - ~/.nvm/versions/node/v18.18.2/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 9.8.1 - ~/.nvm/versions/node/v18.18.2/bin/npm
    pnpm: 8.9.0 - ~/Library/pnpm/pnpm
  npmGlobalPackages:
    netlify-cli: 16.9.3

**Comment by stormwarning** [comment] 2023-11-01 02:17
I'm also getting this same error; is there an upcoming version that fixes this?

**Comment by eduardoboucas** [comment] 2023-11-01 11:07
@stormwarning it's being addressed in https://github.com/netlify/zip-it-and-ship-it/pull/1640. I'll update this issue once there's a new CLI release.

**Comment by stormwarning** [comment] 2023-11-02 17:30
Thanks @eduardoboucas, I just tried the latest version but it's unable to find the symlink

```
Error: ENOENT: no such file or directory, symlink '../../node_modules/.pnpm/rss-to-json@2.1.1/node_modules/rss-to-json' -> '/Users/jnelson/Projects/tidaltheory-www/www/.netlify/functions-serve/letterboxd/node_modules/rss-to-json'

  System:
    OS: macOS 13.5.1
    CPU: (10) arm64 Apple M1 Pro
  Binaries:
    Node: 18.18.2 - ~/.nvm/versions/node/v18.18.2/bin/node
    npm: 9.8.1 - ~/.nvm/versions/node/v18.18.2/bin/npm
  Browsers:
    Chrome: 118.0.5993.117
    Safari: 16.6
  npmGlobalPackages:
    netlify-cli: 17.0.1
```

Maybe because this is in a monorepo setup?

**Comment by eduardoboucas** [comment] 2023-11-06 09:39
@stormwarning sorry to hear you're still experiencing this issue. I've reopened it so we can investigate further.

**Comment by Skn0tt** [comment] 2024-02-12 14:11
Hey @jnschrag! I'd like to look into what's failing for you. You've already shared a bunch about the setup, but I can't spot anything in there that leads to a bug. Could you share a reproduction repository that I can clone and run locally to look at this?

**Comment by jnschrag** [comment] 2024-02-12 17:18
> Hey @jnschrag! I'd like to look into what's failing for you. You've already shared a bunch about the setup, but I can't spot anything in there that leads to a bug. Could you share a reproduction repository that I can clone and run locally to look at this?

Thanks so much! I really appreciate it. Here is a [test repo](https://github.com/jnschrag/sveltekit-function-test) that demonstrates the issue. I did eventually find a workaround that actually works (using a plugin) so I've included that as well.

**Comment by Skn0tt** [comment] 2024-02-13 09:11
Lovely, thanks for providing the repro! I still can't reproduce it on my end, though. Here's the steps I took:

1. clone the repo
2. `npm i`
3. `netlify dev --offline`
4. open `localhost:8888` and click around the page

I did see both functions build just fine, and saw the `publish-chart-background` function be executed correctly as well. Am I holding this wrong? Also, what version of the Netlify CLI are you observing this on? For me, `netlify version` says `netlify-cli/17.16.1 darwin-arm64 node-v20.9.0`. Any chance you're on a different OS, or a different version? What does `netlify version` print for you?

**Comment by jnschrag** [comment] 2024-02-13 16:01
Thanks for looking into it! Very weird that it's working for you, but hopefully that means this is a solvable problem!

I get `netlify-cli/17.15.7 darwin-x64 node-v20.10.0` when I run that, which is an older version. 

Following the same steps you did, I get this message: 
![image](https://github.com/netlify/cli/assets/1896496/9c520a1e-0058-4364-b5d3-0365592a2a0a)

When I first experienced this issue, I was on the latest version of Netlify CLI, but downgraded per the error message suggestion. Updating it to the latest now (17.16.2) gives me the same error message I shared above.

**Comment by ascorbic** [comment] 2024-02-13 17:30
fwiw I just tried to reproduce it, with the same results as @Skn0tt:
![image](https://github.com/netlify/cli/assets/213306/4b854772-9a84-4f1e-a2b1-1c429b2ee81b)

**Comment by jnschrag** [comment] 2024-02-13 18:41
🤔 I left this out of the README, but just want to confirm - did you also install the dependencies in the `chart_template` directory?

**Comment by Skn0tt** [comment] 2024-02-14 11:23
Ha, that's it! Can reproduce now, thank you. I'll do some digging into what's causing this next 👍

**Comment by Skn0tt** [comment] 2024-02-14 11:38
The error message stems from this line: https://github.com/netlify/zip-it-and-ship-it/blob/9e82c5a761d0a00fe92cb8221f7e48756f46d06e/src/runtimes/node/utils/zip.ts#L158-L160

I'll see if I can reproduce this bug within zip-it-and-ship-it alone.

**Comment by Skn0tt** [comment] 2024-02-14 14:11
oh no! didn't want to do that. stupid robots

**Comment by Skn0tt** [comment] 2024-02-14 14:11
https://github.com/netlify/cli/pull/6385, once merged + released, should resolve this

**Comment by jnschrag** [comment] 2024-02-14 15:59
> #6385, once merged + released, should resolve this

Amazing. Thank you so much for looking into this and resolving it so quickly!

**Comment by Skn0tt** [comment] 2024-02-19 15:06
Released as part of https://github.com/netlify/cli/releases/tag/v17.16.3 ! 🥳

**Closed by Skn0tt** 2024-02-19 15:06 UTC
Labels: type: bug, area: functions, area: command: dev
