### ISSUE TITLE
TypeError [ERR_INVALID_ARG_TYPE]: The "url" argument must be of type string. Received undefined

### ISSUE THREAD

**Issue by arnessonpontus** [netlify/cli#2222] opened 2021-04-24 16:06 UTC
**Describe the bug**

Latest release v3.21.9 fails with `TypeError [ERR_INVALID_ARG_TYPE]: The "url" argument must be of type string. Received undefined`

**To Reproduce**

`npm install netlify-cli -g`
`netlify dev`

**Configuration**

N/A

**Expected behavior**

No error. Works in earlier versions (3.19.0).

**CLI Output**
```
TypeError [ERR_INVALID_ARG_TYPE]: The "url" argument must be of type string. Received undefined
    at validateString (internal/validators.js:120:11)
    at Url.parse (url.js:159:3)
    at Object.urlParse [as parse] (url.js:154:13)
    at Object.common.setupOutgoing (/usr/local/lib/node_modules/netlify-cli/node_modules/http-proxy/lib/http-proxy/common.js:100:45)
    at Array.stream (/usr/local/lib/node_modules/netlify-cli/node_modules/http-proxy/lib/http-proxy/passes/web-incoming.js:127:14)
    at ProxyServer.<anonymous> (/usr/local/lib/node_modules/netlify-cli/node_modules/http-proxy/lib/http-proxy/index.js:81:21)
    at Object.web (/usr/local/lib/node_modules/netlify-cli/src/utils/proxy.js:331:20)
    at serveRedirect (/usr/local/lib/node_modules/netlify-cli/src/utils/proxy.js:114:28)
    at ProxyServer.<anonymous> (/usr/local/lib/node_modules/netlify-cli/src/utils/proxy.js:305:14)
    at ProxyServer.emit (/usr/local/lib/node_modules/netlify-cli/node_modules/eventemitter3/index.js:183:35) {
  code: 'ERR_INVALID_ARG_TYPE'
}
TypeError [ERR_INVALID_ARG_TYPE]: The "url" argument must be of type string. Received undefined
    at validateString (internal/validators.js:120:11)
    at Url.parse (url.js:159:3)
    at Object.urlParse [as parse] (url.js:154:13)
    at Object.common.setupOutgoing (/usr/local/lib/node_modules/netlify-cli/node_modules/http-proxy/lib/http-proxy/common.js:100:45)
    at Array.stream (/usr/local/lib/node_modules/netlify-cli/node_modules/http-proxy/lib/http-proxy/passes/web-incoming.js:127:14)
    at ProxyServer.<anonymous> (/usr/local/lib/node_modules/netlify-cli/node_modules/http-proxy/lib/http-proxy/index.js:81:21)
    at Object.web (/usr/local/lib/node_modules/netlify-cli/src/utils/proxy.js:331:20)
    at serveRedirect (/usr/local/lib/node_modules/netlify-cli/src/utils/proxy.js:114:28)
    at ProxyServer.<anonymous> (/usr/local/lib/node_modules/netlify-cli/src/utils/proxy.js:305:14)
    at ProxyServer.emit (/usr/local/lib/node_modules/netlify-cli/node_modules/eventemitter3/index.js:183:35) {
  code: 'ERR_INVALID_ARG_TYPE'
}

/usr/local/lib/node_modules/netlify-cli/node_modules/netlify-redirector/lib/redirects.js:116
      throw ex;
      ^
abort({"code":"ERR_INVALID_ARG_TYPE"}) at Error
    at jsStackTrace (/usr/local/lib/node_modules/netlify-cli/node_modules/netlify-redirector/lib/redirects.js:1070:13)
    at stackTrace (/usr/local/lib/node_modules/netlify-cli/node_modules/netlify-redirector/lib/redirects.js:1087:12)
    at process.abort (/usr/local/lib/node_modules/netlify-cli/node_modules/netlify-redirector/lib/redirects.js:8502:44)
    at process.emit (events.js:315:20)
    at processPromiseRejections (internal/process/promises.js:209:33)
    at processTicksAndRejections (internal/process/task_queues.js:98:32)
```

**Comment by eduardoboucas** [comment] 2021-04-24 23:07
Duplicate of #2216.

**Closed by eduardoboucas** 2021-04-24 23:07 UTC
Labels: type: bug
