### ISSUE TITLE
`netlify deploy` suddenly asking about publish dir

### ISSUE THREAD

**Issue by lindsaylevine** [netlify/cli#1594] opened 2020-11-25 15:32 UTC
**Describe the bug**

i've been deploying from the CLI since i started @ netlify and out of nowhere it started asking me to provide a publish directory at the end 🤔 

![Screen Shot 2020-11-24 at 10 48 02 PM](https://user-images.githubusercontent.com/57350178/100247767-afc37c00-2f08-11eb-825d-b52f36f61cd1.png)

![Screen Shot 2020-11-24 at 10 54 40 PM](https://user-images.githubusercontent.com/57350178/100247765-ae924f00-2f08-11eb-8792-d931191b91f4.png)

**To Reproduce**

1. Clone https://github.com/lindsaylevine/ssp-url-slashes
2. Navigate to the cloned repository
3. Run `netlify deploy --build`
4. See CLI asking for publish dir

**Configuration**

- If possible, please copy/paste below your `netlify.toml`.

```
[build]
  command = "npm run build"

[[plugins]]
  package = "@netlify/plugin-nextjs"

```

- Please enter the following command in a terminal and copy/paste its output:

```bash
npx envinfo --system --binaries --npmPackages netlify-cli --npmGlobalPackages netlify-cli
```

```
System:
    OS: macOS 10.15.4
    CPU: (8) x64 Intel(R) Core(TM) i7-1068NG7 CPU @ 2.30GHz
    Memory: 449.28 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 14.12.0 - /usr/local/bin/node
    Yarn: 1.22.5 - /usr/local/bin/yarn
    npm: 6.14.8 - /usr/local/bin/npm
  npmGlobalPackages:
    netlify-cli: 2.68.6
```

**Expected behavior**

did not expect the CLI to ask me for a publish directory; `netlify deploy --flag` should complete without that prompt and default the publish dir to `.` if not supplied in the .toml

**Comment by erezrokah** [comment] 2020-11-25 16:21
Thanks @lindsaylevine, I don't think that behavior changed in the CLI.
I believe the reason is not wanting to publish the root directory by default unless explicitly permitted to do so by the user, to avoid making possibly private (possibly uncommitted) files public without consent.

Maybe the missing part is the site not having a publish directory configured in Netlify UI?

I was able to reproduce the issue and can confirm setting a publish directory to `.` in the UI solves it.

**Comment by lindsaylevine** [comment] 2020-11-25 16:32
hmm, i remember previously testing without a publish dir configured and it never prompted me with this. but if this is expected behavior then its all good!

**Comment by erezrokah** [comment] 2020-11-25 17:36
Cool, closing this issue.

**Closed by erezrokah** 2020-11-25 17:36 UTC
Labels: type: bug
