### ISSUE TITLE
DX: Make "unprocessable entity" error message nicer

### ISSUE THREAD

**Issue by sw-yx** [netlify/cli#308] opened 2019-04-28 02:30 UTC
"unprocessable entity" error when i give the wrong deploy directory

**- Do you want to request a *feature* or report a *bug*?**
bug

**- What is the current behavior?**
![image](https://user-images.githubusercontent.com/6764957/56857471-08e9b900-693c-11e9-97a5-335b3836fb97.png)

**- What is the expected behavior?**
we need better validation on netlify.toml entries.

**Comment by bcomnes** [comment] 2019-05-01 21:18
Looks like an API error.  Having an invalid path triggers this?  Just confirming.

**Comment by sw-yx** [comment] 2019-05-02 03:01
yes. should be pretty easy to replicate. we shouldnt send it to the API in the first place. i would class this as a low priority bug tho

**Comment by erezrokah** [comment] 2021-05-06 09:28
I tried reproducing this and it didn't error out for me.
It actually set the published directory:
![image](https://user-images.githubusercontent.com/26760571/117275079-59b71500-ae66-11eb-91a4-cfaa7c3da58f.png)

It would be nice to identify such user mistakes, but I can't think of a good way to do it at the moment. 

Closing the issue. Please comment if you think this is still relevant

**Closed by erezrokah** 2021-05-06 09:28 UTC
Labels: area: command: sites, area: dx, low-priority, type: bug
