### ISSUE TITLE
netlify-cli causes `npm audit fix` to fail with EBADPLATFORM error

### ISSUE THREAD

**Issue by dilly-sixmo** [netlify/cli#5536] opened 2023-03-08 13:28 UTC
### Describe the bug

I'm unable to use the `npm audit fix` command after adding `netlify-cli` to my package.

The error is displayed as follows:

```
npm ERR! code EBADPLATFORM
npm ERR! notsup Unsupported platform for @esbuild/android-arm@0.16.17: wanted {"os":"android","arch":"arm"} (current: {"os":"win32","arch":"x64"})
npm ERR! notsup Valid OS:    android
npm ERR! notsup Valid Arch:  arm
npm ERR! notsup Actual OS:   win32
npm ERR! notsup Actual Arch: x64

npm ERR! A complete log of this run can be found in:
```

### Steps to reproduce

Initialize a new project with NPM, add `netlify-cli` as a dependency, and run `npm audit fix`

### Configuration

win32 / x64

### Environment

'envinfo' is not recognized as an internal or external command,
operable program or batch file.

**Comment by danez** [comment] 2023-03-09 14:38
This is a problem of npm. Duplicate of #5323

**Closed by danez** 2023-03-09 14:38 UTC
Labels: type: bug
