### ISSUE TITLE
TypeError: `` is not an Option Object when using plugins.js as a function name

### ISSUE THREAD

**Issue by labboy0276** [netlify/cli#4679] opened 2022-06-06 12:03 UTC
### Describe the bug

Hello

I am currently using the serverless functions to render api end point for https://api.lando.dev/ (lando-api.netlify.app)

My current toml file redirects the base name of all js files in the functions directory to their respective url via:

```
[build]
  functions = "functions"

# API rewrites
[[redirects]]
  from = "/"
  to = "/v1"
  status = 200
[[redirects]]
  from = "/v1/*"
  to = "/.netlify/functions/:splat"
  status = 200
```
So a file names functions/ping.js will redirect to https://api.lando.dev/v1/ping.

The issue at hand is if I name a file plugins.js, I get this error when using the netlify-cli:

```
 ›   TypeError: `` is not an Option Object
```

The error stems from:

```
TypeError: `` is not an Option Object
    at Object.module.exports (/home/john/.nvm/versions/node/v16.15.0/lib/node_modules/netlify-cli/node_modules/merge-options/index.js:164:10)
    at getConfigForFunction (/home/john/.nvm/versions/node/v16.15.0/lib/node_modules/netlify-cli/node_modules/@netlify/zip-it-and-ship-it/dist/config.js:30:36)
    at /home/john/.nvm/versions/node/v16.15.0/lib/node_modules/netlify-cli/node_modules/@netlify/zip-it-and-ship-it/dist/runtimes/index.js:72:65
    at Array.map (<anonymous>)
    at getFunctionsFromPaths (/home/john/.nvm/versions/node/v16.15.0/lib/node_modules/netlify-cli/node_modules/@netlify/zip-it-and-ship-it/dist/runtimes/index.js:70:43)
    at async FunctionsRegistry.listFunctions (/home/john/.nvm/versions/node/v16.15.0/lib/node_modules/netlify-cli/node_modules/@netlify/zip-it-and-ship-it/dist/main.js:25:26)
    at async FunctionsRegistry.scan (/home/john/.nvm/versions/node/v16.15.0/lib/node_modules/netlify-cli/src/lib/functions/registry.js:175:23)
TypeError: `` is not an Option Object
    at Object.module.exports (/home/john/.nvm/versions/node/v16.15.0/lib/node_modules/netlify-cli/node_modules/merge-options/index.js:164:10)
    at getConfigForFunction (/home/john/.nvm/versions/node/v16.15.0/lib/node_modules/netlify-cli/node_modules/@netlify/zip-it-and-ship-it/dist/config.js:30:36)
    at /home/john/.nvm/versions/node/v16.15.0/lib/node_modules/netlify-cli/node_modules/@netlify/zip-it-and-ship-it/dist/runtimes/index.js:72:65
    at Array.map (<anonymous>)
    at getFunctionsFromPaths (/home/john/.nvm/versions/node/v16.15.0/lib/node_modules/netlify-cli/node_modules/@netlify/zip-it-and-ship-it/dist/runtimes/index.js:70:43)
    at async FunctionsRegistry.listFunctions (/home/john/.nvm/versions/node/v16.15.0/lib/node_modules/netlify-cli/node_modules/@netlify/zip-it-and-ship-it/dist/main.js:25:26)
    at async FunctionsRegistry.scan (/home/john/.nvm/versions/node/v16.15.0/lib/node_modules/netlify-cli/src/lib/functions/registry.js:175:23)

/home/john/.nvm/versions/node/v16.15.0/lib/node_modules/netlify-cli/node_modules/netlify-redirector/lib/redirects.js:116
      throw ex;
      ^
abort({}) at Error
    at jsStackTrace (/home/john/.nvm/versions/node/v16.15.0/lib/node_modules/netlify-cli/node_modules/netlify-redirector/lib/redirects.js:1070:13)
    at stackTrace (/home/john/.nvm/versions/node/v16.15.0/lib/node_modules/netlify-cli/node_modules/netlify-redirector/lib/redirects.js:1087:12)
    at process.abort (/home/john/.nvm/versions/node/v16.15.0/lib/node_modules/netlify-cli/node_modules/netlify-redirector/lib/redirects.js:8502:44)
    at process.emit (node:events:527:28)
    at emit (node:internal/process/promises:140:20)
    at processPromiseRejections (node:internal/process/promises:274:27)
    at processTicksAndRejections (node:internal/process/task_queues:97:32)
(Use `node --trace-uncaught ...` to show where the exception was thrown)
```

If I rename the file to anything else, it works just fine, just not when I use the plugins namespace. So is the plugins namespace a protected /reserved namespace/path on netlify?

### Steps to reproduce

Name a file plugins.js in your functions folder with the toml file:

```
[build]
  functions = "functions"

# API rewrites
[[redirects]]
  from = "/"
  to = "/v1"
  status = 200
[[redirects]]
  from = "/v1/*"
  to = "/.netlify/functions/:splat"
  status = 200
```

then run `netlify dev`

### Configuration

```
[build]
  functions = "functions"

# API rewrites
[[redirects]]
  from = "/"
  to = "/v1"
  status = 200
[[redirects]]
  from = "/v1/*"
  to = "/.netlify/functions/:splat"
  status = 200
```

### Environment

```
  System:
    OS: Linux 5.17 Pop!_OS 20.04 LTS
    CPU: (16) x64 Intel(R) Core(TM) i7-10875H CPU @ 2.30GHz
    Memory: 26.81 GB / 31.23 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 16.15.0 - ~/.nvm/versions/node/v16.15.0/bin/node
    Yarn: 1.22.17 - ~/.yarn/bin/yarn
    npm: 8.5.5 - ~/.nvm/versions/node/v16.15.0/bin/npm
  npmGlobalPackages:
    netlify-cli: 10.4.0
```

**Comment by minivan** [comment] 2022-06-18 08:30
Thanks for reporting @labboy0276 . I'm adding `needs docs` because if this is indeed a limitation on the filename, we _might_ want to highlight that in the docs and the CLI itself.

**Comment by JWhist** [comment] 2022-06-24 14:59
```{
  build: {
    edge_functions: '/Users/jordanwhistler/denoError/netlify/edge-functions',
    environment: {},
    publish: '/Users/jordanwhistler/denoError/dist/angular-quickstart',
    publishOrigin: 'config',
    processing: { css: {}, html: {}, images: {}, js: {} },
    services: {},
    command: 'ng build',
    commandOrigin: 'config',
    base: undefined,
    functions: '/Users/jordanwhistler/denoError/functions'
  },
  redirectsOrigin: 'config',
  functions: { '*': {} },
  plugins: [],
  functionsDirectory: '/Users/jordanwhistler/denoError/functions',
  functionsDirectoryOrigin: 'config-v1',
  headers: [],
  redirects: [
    {
      from: '/',
      query: {},
      to: '/v1',
      status: 200,
      force: false,
      conditions: {},
      headers: {}
    },
    {
      from: '/v1/*',
      query: {},
      to: '/.netlify/functions/:splat',
      status: 200,
      force: false,
      conditions: {},
      headers: {}
    }
  ]
}
```

At first glance, after toying around, it would appear that naming a function with any of the top level properties of this config object will cause the builder to attempt to import that value as the function itself.  So in the cause of `plugins.js`, because it defaults to an empty array, it is not matching the object type in the module being used, which checks for object creation using `{}` or `new Object()` etc.  

For instance, by creating a function called `functionsDirectory.js`, I get this error instead when running netlify dev: 

```
◈ Netlify Dev ◈
◈ Ignored general context env var: LANG (defined in process)
 ›   TypeError: `/Users/jordanwhistler/denoError/functions` is not an Option Object
```

where it appears to be actually injecting the directory path itself as the value of the function.  Oddly enough, this only applies to _some_ of the properties, errors appear when using `plugins`, `headers`, `functionsDirectory`, `functionsDirectoryOrigin` and `redirects` that I've seen so far.

**Comment by JWhist** [comment] 2022-06-24 17:53
Traced the error to this function: https://github.com/netlify/zip-it-and-ship-it/blob/4ba670c07e7331a1fdcb61143cf01e0181d12ea9/src/utils/matching.ts#L28 which comes from an imported library and uses a module called `merge_options` (see stack trace above).  This expects an object containing properties to be merged, but we are passing in an array in the case of https://github.com/netlify/zip-it-and-ship-it/blob/4ba670c07e7331a1fdcb61143cf01e0181d12ea9/src/config.ts#L26 containing matches, which occurs when `func.name` matches one of the object keys of the `config` object.  Wrapping the array in an object appears to solve this, and I am able to run `ntl dev` locally by doing so with no problems.

**Comment by JWhist** [comment] 2022-06-28 13:26
After further investigation, the issue lies further up the stack and isn't a result of this `mergeOptions` call, but instead appears to be related to the config as a whole getting passed in to the function in those cases mentioned above.

**Comment by JWhist** [comment] 2022-07-08 19:48
Removing the needs docs label, since this was a logical glitch and not anything that needs to updated for the customer facing docs.

**Closed** 2022-07-11 14:16 UTC
Labels: good first issue, type: bug, area: functions
