### ISSUE TITLE
Please replace with a clear and descriptive title

### ISSUE THREAD

**Issue by simonmulser** [netlify/cli#1543] opened 2020-11-09 17:40 UTC
**Is your feature request related to a problem? Please describe.**

It is currently not possbile to pass something else then a stringifyed JSON object to the `--payload` option of `ntl functions:invoke`. Paddle eg. uses in their Webhooks bodies a querystring representation of the data - eg.: `firstname=nobody&lastname=somebody`.

**Describe the solution you'd like**

Possibility to pass anything as payload to the function with `--payload` or maybe a second option like `--payload-unchecked` which doesn't do checks in the background.

**Can you submit a pull request?**

Yes.

> Pull requests are welcome! If you would like to help us add this feature, please check our
> [contributions guidelines](../../CONTRIBUTING.md).

**Comment by erezrokah** [comment] 2020-11-09 17:44
Hi @simonmulser, thank you for opening this issue.
Closing it as a duplicate of https://github.com/netlify/cli/issues/980.
Please comment if you think this is not a duplicate.

**Closed by erezrokah** 2020-11-09 17:44 UTC
Labels: type: feature
