### ISSUE TITLE
wasm streaming compile failed: TypeError: Failed to parse URL from /usr/lib/node_modules/netlify-cli/node_modulesPlease replace with a clear and descriptive title

### ISSUE THREAD

**Issue by fadyio** [netlify/cli#4610] opened 2022-05-14 21:07 UTC
### Describe the bug

The following appear each time I run netlify login

```
(node:114335) ExperimentalWarning: The Fetch API is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
wasm streaming compile failed: TypeError: Failed to parse URL from /usr/lib/node_modules/netlify-cli/node_modules/netlify-redirector/lib/redirects.wasm
falling back to ArrayBuffer instantiation
Logging into your Netlify account...
Opening https://app.netlify.com/authorize?response_type=ticket&ticket=b78d6555d553a6a1de5f7c7d3dd4e8ec
⠋ Waiting for authorization.../usr/lib/node_modules/netlify-cli/node_modules/netlify-redirector/lib/redirects.js:116
      throw ex;
      ^

Error: spawn /usr/bin/palemoon ENOENT
    at ChildProcess._handle.onexit (node:internal/child_process:283:19)
    at onErrorNT (node:internal/child_process:476:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
Emitted 'error' event on ChildProcess instance at:
    at ChildProcess._handle.onexit (node:internal/child_process:289:12)
    at onErrorNT (node:internal/child_process:476:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  ```

### Steps to reproduce

Run `netlify status`.

### Configuration

None.

### Environment

  System:
    OS: Linux 5.15 Manjaro Linux
    CPU: (4) x64 Intel(R) Core(TM) i5-3570 CPU @ 3.40GHz
    Memory: 5.33 GB / 9.60 GB
    Container: Yes
    Shell: 5.8.1 - /usr/bin/zsh
  Binaries:
    Node: 18.1.0 - /usr/bin/node
    Yarn: 1.22.15 - /usr/bin/yarn
    npm: 8.9.0 - /usr/bin/npm
  npmGlobalPackages:
    netlify-cli: 10.3.1

**Comment by tinfoil-knight** [comment] 2022-08-24 18:51
Duplicate of https://github.com/netlify/cli/issues/4609

**Closed by tinfoil-knight** 2022-08-24 18:51 UTC
Labels: status: duplicate, type: bug, 🏡 upkeep
