### ISSUE TITLE
Unable to upgrade 

### ISSUE THREAD

**Issue by smoreau-tj** [netlify/cli#3907] opened 2021-12-23 14:33 UTC
**Describe the bug**

Unable to upgrade netlify-cli  8.1.8 to 8.4.2 
it seems eslint-plugin-local-rules was pointing to file:tools/eslint-rules

__attempted ways to fix:__
 - reinstall netlify-cli: failed same error
 - installing eslint-plugin-local-rules: failed would continued to look for eslint-plugin-local-rules
 - removing netlify-cli manually and reinstalling: worked 

**To Reproduce**

Run `npm i -g netlify-cli`

1. Run `git clone git@github.com:owner/repo-with-cli-bug.git`
2. Navigate to the cloned repository
3. Run `netlify dev`
4. See that the CLI exits with an error

**Configuration**

- If possible, please copy/paste below your `netlify.toml`. `N/A`
- Please enter the following command in a terminal and copy/paste its output:

```bash
npx envinfo --system --binaries --npmPackages netlify-cli --npmGlobalPackages netlify-cli
```

output: 
```bash
  System:
    OS: macOS 12.1
    CPU: (8) x64 Apple M1
    Memory: 33.45 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.18.2 - ~/.nvm/versions/node/v14.18.2/bin/node
    Yarn: 1.22.17 - /opt/homebrew/bin/yarn
    npm: 6.14.15 - ~/.nvm/versions/node/v14.18.2/bin/npm
    Watchman: 2021.12.20.00 - /opt/homebrew/bin/watchman
  npmGlobalPackages:
    netlify-cli: 8.1.8
```
**Expected behavior**
Cli would upgrade

**CLI Output**

If applicable, add the CLI output to help explain your problem.
```bash npm WARN checkPermissions Missing write access to /Users/sergemoreau/.nvm/versions/node/v14.18.2/lib/node_modules/netlify-cli/node_modules/eslint-plugin-local-rules
npm ERR! code ENOENT
npm ERR! syscall access
npm ERR! path /Users/sergemoreau/.nvm/versions/node/v14.18.2/lib/node_modules/netlify-cli/node_modules/eslint-plugin-local-rules
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, access '/Users/sergemoreau/.nvm/versions/node/v14.18.2/lib/node_modules/netlify-cli/node_modules/eslint-plugin-local-rules'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
➜  tj-bc git:(setup/sitemap) ✗ '/Users/sergemoreau/.nvm/versions/node/v14.18.2/lib/node_modules/netlify-cli
'```
https://d.pr/i/QoP2dT

**Additional context**

Add any other context about the problem here.

**Comment by erezrokah** [comment] 2021-12-30 13:59
Hi @smoreau-tj, I believe this is a duplicate of https://github.com/netlify/cli/issues/3869 and was resolved in https://github.com/netlify/cli/pull/3872.

We no longer reference `eslint-plugin-local-rules` in our `package.json`.

Do you mind verifying the issue still exists? Another possible solution is to update `npm` to the latest version via `npm install -g npm`.

**Comment by smoreau-tj** [comment] 2021-12-30 23:10
@erezrokah I had been able to remove by manually deleting netlify-cli from my npm global packages

**Closed** 2022-01-03 10:05 UTC
Labels: type: bug
