### ISSUE TITLE
Invalid Content-Type for Netlify Dev forms request

### ISSUE THREAD

**Issue by philiplindberg** [netlify/cli#1279] opened 2020-09-24 14:06 UTC
**Describe the bug**

When running Netlify Functions locally via `netlify dev` and making a `POST` request to a function endpoint, I'm getting the following console error:

```
Invalid Content-Type for Netlify Dev forms request
```

**To Reproduce**

1. Generate a new netlify function using `netlify functions:create hello-world`
2. Pick `[hello-world]` template
3. Serve newly created function locally with `netlify dev`
4. Make request to local function endpoint (using Postman, curl etc...)
   * Set method to `POST`
   * Add header: `Content-Type: applications/json`
5. Response will contain `Invalid Content-Type for Netlify Dev forms request` error

**Configuration**

Using `netlify-cli@2.64.1`.

netlilfy.toml:
```
[build]
  functions = "functions"
```

envinfo:
```
System:
    OS: macOS 10.15.6
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
    Memory: 183.36 MB / 32.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.18.2 - ~/.nvm/versions/node/v12.18.2/bin/node
    Yarn: 1.22.5 - ~/.nvm/versions/node/v12.18.2/bin/yarn
    npm: 6.14.5 - ~/.nvm/versions/node/v12.18.2/bin/npm
```

**Expected behavior**

No error.

**Comment by Xaconi** [comment] 2020-10-11 17:20
+1

**Comment by masonhipp** [comment] 2020-10-15 22:05
Also getting this error

**Comment by sandman18** [comment] 2020-10-19 18:37
+1

**Comment by jasperchess** [comment] 2020-10-24 08:52
Also getting this error.

I've reverted back to using `netlify-lambda serve` for the time being

**Comment by Dimotro** [comment] 2020-11-09 09:46
I'm still experiencing exactly this error as described on:
netlify-cli/2.68.0 linux-x64 node-v14.15.0

**Comment by ksnyde** [comment] 2020-12-07 23:50
This is actually quite shocking. POST is critical to almost any RESTful API and from what I'm seeing I can send a request via GET, PUT, DELETE, etc. and it all works as expected. Using POST however returns the `Invalid Content-Type for Netlify Dev forms request` message to the node server console.

To this point, my testing has been within the `netlify dev` sandbox. Will try in a post-deploy environment soon too but for testing purposes it really needs to work in both environments anyway.

**Comment by ksnyde** [comment] 2020-12-07 23:52
I can validate that `POST` _does_ work once deployed but `netlify dev` is broken

**Comment by beeetooo** [comment] 2021-01-23 22:28
+1

**Comment by zen1** [comment] 2021-02-02 22:19
+1

**Comment by thomashibbard** [comment] 2021-02-07 02:03
+1

**Comment by erezrokah** [comment] 2021-02-07 10:34
Hi all please upvote the issue by clicking the upvote button 👍  - that way we can sort it by upvotes when looking for issues to resolve.

**Comment by erezrokah** [comment] 2021-02-10 16:38
Hi all, I couldn't reproduce this issue using the original reproduction scenario and the latest CLI version `netlify-cli v3.7.1`.

I'm using the following command:
`curl -i -d "{}" -H"Content-Type: application/json"  http://localhost:<port>/.netlify/functions/hello-world ` and the `hello-world` example (I also tried with `applications/json` as the original issue suggests - notice the extra `s` in `applications`).

> Note that `-d` [implies](https://daniel.haxx.se/blog/2015/09/11/unnecessary-use-of-curl-x/) a `POST` request

**Comment by erezrokah** [comment] 2021-02-14 14:50
Closing this issue. If you're still experiencing it please comment with a reproduction scenario

**Comment by gitdagray** [comment] 2021-02-25 00:33
Installed Netlify CLI today (netlify-cli/3.8.6 win32-x64 node-v14.15.4). This issue still exists. To reproduce, make a simple POST request to a Netlify serverless function with body data. I think most will want to send JSON. I am using an example from the Netlify site examples that assigns the params from the body: 
exports.handler = async (event, context) => {
const params = querystring.parse(event.body);
} 
I don't think it gets that far. I get the same error reported above every time.

**Comment by hwlmatt** [comment] 2021-02-25 03:45
hey @erezrokah, definitely seeing this using Postman.

`POST` request on `localhost` with raw `JSON` body receives the `Invalid Content-Type for Netlify Dev forms request` error.

no issue with `GET` or `PUT`.

`netlify-cli/3.8.6 darwin-x64 node-v12.18.3`

**Comment by erezrokah** [comment] 2021-02-25 10:07
Hi @hwlmatt can you provide a public repo with a reproduction? I'm probably missing something with my setup

**Comment by hwlmatt** [comment] 2021-02-25 15:21
> Hi @hwlmatt can you provide a public repo with a reproduction? I'm probably missing something with my setup

@erezrokah Sure thing. This reproduces it for me. README has the steps & cURL command etc.

https://github.com/hwlmatt/netlify-cli-issue.git

**Comment by erezrokah** [comment] 2021-03-01 13:03
> @erezrokah Sure thing. This reproduces it for me. README has the steps & cURL command etc.

Re-opened the issue per https://github.com/netlify/cli/issues/1279#issuecomment-785981336.
@hwlmatt please note that the reproduction in that repo is different - you're not sending the request to the function endpoint.
`http://localhost:<port>/example` should be `http://localhost:<port>/.netlify/functions/example`

**Comment by mfuery** [comment] 2021-03-02 22:14
FWIW I was getting the same error "Invalid Content-Type for Netlify Dev forms request" when my POST url was of the form:
`http://localhost:<port>/example`
It works after I corrected that url per @erezrokah 
`http://localhost:<port>/.netlify/functions/example`
Thanks!

**Comment by erezrokah** [comment] 2021-03-03 09:16
We have a fix pending https://github.com/netlify/cli/pull/1949 to provide the relevant error message when this happens.

**Closed** 2021-03-03 10:03 UTC
Labels: area: command: dev, area: forms, type: bug
