### ISSUE TITLE
Netlify Functions not receiving a body in local dev but works once deployed to Netlify

### ISSUE THREAD

**Issue by mclimb** [netlify/cli#5030] opened 2022-09-07 13:26 UTC
### Describe the bug

When I submit a fetch in from my Next.js app in local development using netlify dev (local node version v17.4.0), the Netlify Function runs but the body in the event is always `undefined`. I expect it to be `{ url: "websiteUrl" }`. When I deployed the function to Netlify it correctly found and parsed the body.

I noticed this occur on both background and regular functions.

I submitted more details about this issue here: https://answers.netlify.com/t/why-arent-my-netlify-functions-finding-a-body/74661 

### Steps to reproduce

1. Run `git clone git@github.com:mclimb/jamhack-personalized-demo.git` (private repo, ask Mike Chirokas for access)
2. Install npm packages 
3. netlify dev
4. Go localhost:8888
5. Submit to any function endpoint, for example, enter the website url as `https://miro.com/` and click the color pallet button (this will try to get the colors on https://miro.com/) and should call the function getBrandColors which should take the url body

### Environment

```
System:
    OS: macOS 12.5.1
    CPU: (8) arm64 Apple M1
    Memory: 756.27 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 17.4.0 - ~/.nvm/versions/node/v17.4.0/bin/node
    Yarn: 1.22.17 - ~/.nvm/versions/node/v17.4.0/bin/yarn
    npm: 8.3.1 - ~/.nvm/versions/node/v17.4.0/bin/npm
  npmGlobalPackages:
    netlify-cli: 11.5.1
```

**Comment by PhilBookst** [comment] 2022-09-11 11:34
Getting the same error, also on a M1 Mac in dev mode.

Netlify-cli: `netlify-cli/11.7.1 darwin-x64 node-v16.13.2`

**Comment by sarahetter** [comment] 2022-09-20 17:52
Alright! Things I've tried to investigate if this has anything to do with next-runtime

1. Removed all code from next-runtime that we're running in `onPreDev` - error still occurs (no body sent)
2. Commented out the line in the cli that adds a plugin during dev (currently line 476 in `src/commands/dev/dev.js`: 
```
      // cachedConfig.config.plugins = [...newPlugins, ...cachedConfig.config.plugins]
```
which still gives the same error - the next-runtime isn't being run during dev, but the body is still not being sent. 

So this leads me to think it's something that is a bug in the cli, or at the very least something we're *not* doing in the next-runtime that we should be in next.

**Comment by cetchells** [comment] 2022-09-21 10:38
I get the same body undefined when posting to function:
`netlify-cli/11.8.0 darwin-x64 node-v14.20.0`
Maybe a Mac OS issue, it works fine on windows

**Comment by tinfoil-knight** [comment] 2022-09-21 13:06
@mclimb Can you give me read access to the repository?

**Comment by analiamokbb** [comment] 2022-09-22 18:44
Also encountering the same issue with the latest version of Netlify CLI:

`netlify-cli/11.8.2 darwin-x64 node-v16.8.0`

**Comment by cetchells** [comment] 2022-09-23 09:26
It seems like its actually Content-Length that is undefined, the body is actually there in the request but you check content-length header. If I remove the check for content length it works.
https://github.com/netlify/cli/blob/fc2030468cab8a402c544a702e03e8629d542313/src/lib/functions/server.js#L71
I'm using axios to send the request

**Comment by tinfoil-knight** [comment] 2022-09-23 14:36
@analiamokbb Could you provide a repository with the reproduction of the issue? I was trying to reproduce this issue but wasn't able to with the http client (HTTPie) that I'm using.

---

@cetchells Could you provide me the exact axios request you're using?

**Comment by tinfoil-knight** [comment] 2022-09-24 13:10
@mclimb I made a simple reproduction similar to how you've described things in [why-arent-my-netlify-functions-finding-a-body](https://answers.netlify.com/t/why-arent-my-netlify-functions-finding-a-body/74661) here: https://github.com/KK-Learning-Gym/5030-no-body (haven't used Next.js though)

I'm able to get the request body. I've attached the terminal output here.

```
Request from ::1: POST /.netlify/functions/createDemoData-background
◈ Queueing background function createDemoData-background for execution
Response with status 202 in 1 ms.
{
  path: '/.netlify/functions/createDemoData-background',
  httpMethod: 'POST',
  queryStringParameters: {},
  multiValueQueryStringParameters: {},
  headers: {
    'x-forwarded-for': '::1',
    'accept-language': 'en-GB,en;q=0.9',
    'accept-encoding': 'gzip, deflate, br',
    referer: 'http://localhost:8888/',
    'sec-fetch-dest': 'empty',
    'sec-fetch-mode': 'cors',
    'sec-fetch-site': 'same-origin',
    origin: 'http://localhost:8888',
    accept: '*/*',
    'content-type': 'application/json',
    'sec-ch-ua-platform': '"macOS"',
    'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36',
    'sec-ch-ua-mobile': '?0',
    dnt: '1',
    'sec-ch-ua': '"Google Chrome";v="105", "Not)A;Brand";v="8", "Chromium";v="105"',
    'content-length': '20',
    connection: 'close',
    host: 'localhost:8888',
    'client-ip': '::1'
  },
  multiValueHeaders: {
    'x-forwarded-for': [ '::1' ],
    'accept-language': [ 'en-GB,en;q=0.9' ],
    'accept-encoding': [ 'gzip, deflate, br' ],
    referer: [ 'http://localhost:8888/' ],
    'sec-fetch-dest': [ 'empty' ],
    'sec-fetch-mode': [ 'cors' ],
    'sec-fetch-site': [ 'same-origin' ],
    origin: [ 'http://localhost:8888' ],
    accept: [ '*/*' ],
    'content-type': [ 'application/json' ],
    'sec-ch-ua-platform': [ '"macOS"' ],
    'user-agent': [
      'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36'
    ],
    'sec-ch-ua-mobile': [ '?0' ],
    dnt: [ '1' ],
    'sec-ch-ua': [
      '"Google Chrome";v="105", "Not)A;Brand";v="8", "Chromium";v="105"'
    ],
    'content-length': [ '20' ],
    connection: [ 'close' ],
    host: [ 'localhost:8888' ],
    'client-ip': [ '::1' ]
  },
  body: '{"url":"websiteUrl"}',
  isBase64Encoded: false,
  rawUrl: 'http://localhost:8888/.netlify/functions/createDemoData-background',
  rawQuery: ''
}
body {"url":"websiteUrl"}
◈ Done executing background function createDemoData-background
^C
```

Could you add me to the repository to help me debug your issue better?

**Comment by analiamokbb** [comment] 2022-10-12 19:49
Sorry for the late response. It may take awhile before I can setup an example repository, but the more exact environment conditions:

- Next.js 12.3.1
	- No middleware implementations
- Netlify CLI 12.0.8
- @netlify/plugin-nextjs 4.25.0
- axios 0.27.2
	- All axios requests to a netlify function manually configure 2 headers:  `Authorization: Bearer $token` and `Content-Type: application/json`
- Netlify function source files are under a custom directory and built with webpack 5
	- configuration is the same as what's generated in netlify-lambda
	- Issue was also occurring when using `netlify-lambda` cli
- Typescript 4.5.2

I was able to verify that downgrading only the cli to 10.18.0 does not produce the issue. 11.0.0+ onward does cause an undefined response body.

Upgrading axios to 1.x does not resolve the issue.

**Comment by analiamokbb** [comment] 2022-10-13 18:48
The following repo contains a reproduction of the issue: https://github.com/analiamokbb/next-netlify-example

Axios request can be seen in the [Test](https://github.com/analiamokbb/next-netlify-example/blob/main/components/Test.tsx) component. Note: We do see the issue occurring for both GET and POST requests.

**Comment by Kyrremann** [comment] 2022-10-16 11:43
This seems to be fixed in `v12.0.9`. At least the problem disappeared  when I upgraded from `v12.0.5`.

**Comment by jasoncarrillo0** [comment] 2022-10-19 05:41
I upgraded to `v12.0.9` and it did not fix the problem for me.

**Comment by jasoncarrillo0** [comment] 2022-10-19 06:45
I upgraded to `v12.0.9` and it did not fix the problem for me, it definitely is a bug. I created a workaround that isn't "hacky": just use queryStringParameters instead of sending JSON. I verified it works on both local development and production environments.

Example:

    const json = { username: "me" };  
    const searchParams = '?' + new URLSearchParams(json).toString();  
    const response = await fetch("http://myurl.com/" + searchParams);

Now in your function `event.queryStringParameters` will contain the json.

**Comment by hongchiong** [comment] 2022-10-20 09:29
This issue has been bothering me for weeks. I got it to work by downgrading netlify-cli to version 10.
`npm i -g netlify-cli@10`

**Comment by tinfoil-knight** [comment] 2022-10-21 14:20
> I upgraded to `v12.0.9` and it did not fix the problem for me, it definitely is a bug.

@jasoncarrillo0 Was this only for `GET` requests or for `POST` requests too?

**Comment by jasoncarrillo0** [comment] 2022-10-21 14:26
@tinfoil-knight only used with `GET`, but netlify functions don't seem to care which REST method you use

**Comment by tinfoil-knight** [comment] 2022-10-21 14:28
> @tinfoil-knight only used with `GET`, but netlify functions don't seem to care which REST method you use

@jasoncarrillo0 This might not be related to Netlify CLI. Most client-side libraries (on the browser) just don't support sending a request body with `GET` requests. Could you update the Netlify CLI package & try again with a `POST` request using fetch?

**Comment by thedavidthomas** [comment] 2022-11-14 06:48
I ran into the same issue `netlify functions:serve` has a body for POST requests as expected
However when using`netlify dev` or `netlify dev --live` the event.body is undefined.

**Comment by tinfoil-knight** [comment] 2022-11-14 06:58
@thedavidthomas Are the requests made by your website to the functions `GET` requests? If yes, could you change them to one of these HTTP request methods: `PUT`, `POST`, `DELETE`, and `PATCH` & see if you're still experiencing the issue?

**Comment by thedavidthomas** [comment] 2022-11-14 07:06
Hi @tinfoil-knight 

netlify-cli/12.1.1 darwin-x64 node-v16.17.0

I'm using the `POST` method

my simple function takes the body and returns it in the response
```
const handler = async event => {
  return {
    statusCode: 200,
    body: JSON.stringify({
      message: event.body,
    }),
  };
};

module.exports = {handler};
```

with `netlify dev` 
<img width="957" alt="Screen Shot 2022-11-14 at 3 03 22 pm" src="https://user-images.githubusercontent.com/2648750/201596116-be79ac35-db5f-42c4-bb51-b09e6183f1ca.png">

with `netlify functions:serve`
<img width="957" alt="Screen Shot 2022-11-14 at 3 03 22 pm" src="https://user-images.githubusercontent.com/2648750/201596160-3fa127b6-4f47-4780-a160-cb300b502fc4.png">

as you can see with `netlify dev` the response is empty, where i would expect it to be the same as `functions:serve`

**Comment by tinfoil-knight** [comment] 2022-11-18 18:19
@thedavidthomas That's a bit strange. I wasn't able to replicate this on my end. Create a simple function to return the request body as you've suggested & I'm getting the expected response for both `dev` & `functions:serve`. 

Could you share a repo with the reproduction of the issue?

**Comment by marquez138** [comment] 2022-11-18 21:17
any luck on getting this fixed? having the same issue - Thanks

**Comment by tinfoil-knight** [comment] 2022-11-19 11:29
@marquez138 I'm having trouble reproducing this issue. If you could provide a public repo with a reproduction of the issue, that'd be great.

**Comment by tinfoil-knight** [comment] 2022-11-27 09:13
@danez Can you take a look here & see if you're able to reproduce this issue?

For me, both `netlify dev` & `netlify functions:serve` send the expected response body for HTTP `POST` requests.

**Comment by l5t** [comment] 2022-12-03 07:26
Like @thedavidthomas, I have the exact same behavior. I got the header but the body is `undefined`

**Closed as completed** 2022-12-06 15:11 UTC
Labels: type: bug

**Comment by danez** [comment] 2022-12-06 17:32
This is fixed in https://github.com/netlify/cli/releases/tag/v12.2.9 🌻

**Comment by parkerthegeniuschild** [comment] 2022-12-10 01:48
hallelujah! t'was driving me nuts having to work locally with stubbed requests and responses.
