### ISSUE TITLE
Netlify Dev: process.env missing variables from netlify.toml [dev] block

### ISSUE THREAD

**Issue by oles** [netlify/cli#982] opened 2020-07-13 20:05 UTC
**- Do you want to request a _feature_ or report a _bug_?**
Seems like this is a bug. If it is not, this is a feature I'd like.
It also seems like many other people are looking for this, based on my random searches to find a solution.

**- What is the current behavior?**
Currently, if your netlify.toml file contains
```
...

[dev]
    environment = { NODE_ENV = "development" }

...
```
all the variables specified has seemingly no effect - not only the `NODE_ENV` key.

**- If the current behavior is a bug, please provide the steps to reproduce.**
 - clone https://github.com/oles/netlify-dev-missing-env
 - run `netlify dev`
 - open http://localhost:8888/.netlify/functions/example-function
 - see in console: `NODE_ENV: undefined`

**- What is the expected behavior?**
For the console to log `NODE_ENV: development`

**- Local Environment Information**
```
────────────────────┐
 Environment Info   │
────────────────────┘

  System:
    OS: Linux 5.7 Arch Linux
    CPU: (4) x64 Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz
  Binaries:
    Node: 10.20.1 - /usr/bin/node
    npm: 6.14.6 - /usr/bin/npm
  Browsers:
    Firefox: 78.0.2
  npmGlobalPackages:
    netlify-cli: 2.58.0

netlify-cli/2.58.0 linux-x64 node-v10.20.1
```

**Comment by jonathan-mothership** [comment] 2020-11-17 17:02
I have this issue as well, the `[build.environment]` section in the `netlify.toml` file is completely ignored using `netlify dev` which, at least for us, obliterates the value of using the Netlify CLI. We're forced to have another copy of the vars in a `.env` file due to the number of env vars we use which just causes pains when forgetting to change both. 

```toml
[build.environment]
  NARF="zonk"
```
```bash
yarn netlify dev:exec env | grep zonk
```
```bash
yarn netlify dev -c env | grep zonk
```
Neither command seems to pull from the `netlify.toml` file. 

Is this expected behavior? What's the value of `netlify dev` if it doesn't use the `[build.environment]`?

**Comment by erezrokah** [comment] 2020-11-18 13:57
Thanks for adding this information @jonathan-mothership, we are working on aligning this logic between the CLI and Netlify build system. See https://github.com/netlify/build/pull/2040

**Comment by eduardoboucas** [comment] 2021-01-15 10:04
Hi @oles and @jonathan-mothership! This should be fixed via https://github.com/netlify/cli/pull/1722 and available in the latest version of the CLI.

If something isn't work as expected, feel free to reopen the issue. Thanks!

**Closed by eduardoboucas** 2021-01-15 10:04 UTC
Labels: area: command: dev, area: functions, status: unconfirmed, type: bug
