### ISSUE TITLE
Netlify Dev function hot-reloading (via netlify-lambda) does not work when a --config flag is set

### ISSUE THREAD

**Issue by jimmend** [netlify/cli#1771] opened 2021-01-19 00:34 UTC
**Describe the bug**

It appears that the --config flag on my netlify-lambda build script is causing the "netlify dev" command not to work properly.

**To Reproduce**

1. I have the following script to build netlify functions (from package.json):

`"compile-lambda": "netlify-lambda build src/functions"
`

Then, when I run the "netlify dev" command, the process finds the script and runs it properly:
```
◈ Function builder netlify-lambda detected: Running npm script compile-lambda
 »   Warning: ◈ This is a beta feature, please give us feedback on how to improve at https://github.com/netlify/cli/
◈ Function builder netlify-lambda building functions from directory src/functions
```
At this point, whenever I edit and save a file in the src/functions folder, I get the following:

```
◈ Function builder netlify-lambda building functions from directory src/functions
◈ file.js modified, reloading...
◈ file.js modified, successfully reloaded!
```

However, when I add the --config flag to the "compile-lambda" script, like so:

`"compile-lambda": "netlify-lambda build src/functions --config webpack.functions.config.js"
`

Then, it appears that it is now watching the config file for changes:

```
◈ Function builder netlify-lambda detected: Running npm script compile-lambda
 »   Warning: ◈ This is a beta feature, please give us feedback on how to improve at https://github.com/netlify/cli/
◈ Function builder netlify-lambda building functions from directory webpack.functions.config.js
```

Note that "webpack.functions.config.js" (in the last line above) is not the functions directory but the name of my config file. 

**Expected behavior**

It would be nice if I could add a --config flag and also get the hot-reloading functionality.

Thanks!

**Comment by erezrokah** [comment] 2021-01-19 10:57
Thanks @jimmend for reporting. Do you mind sharing the CLI version you're using? You can get the version by running `ntl --version`

Related to https://github.com/netlify/cli/issues/1726

**Comment by jimmend** [comment] 2021-01-19 17:14
`netlify-cli/3.2.3 win32-x64 node-v14.15.3`

Also, I realized that the hot-reloading works when I make a change to the webpack.config file.  

So it looks like the issue is that the build system is watching for changes in the config file instead of the function source files.

**Comment by erezrokah** [comment] 2021-01-21 15:27
Closing as a duplicate of #1726.
This should be fixed in https://github.com/netlify/cli/releases/tag/v3.4.1

**Closed by erezrokah** 2021-01-21 15:27 UTC
Labels: area: command: dev, area: functions, type: bug
