### ISSUE TITLE
content encoding error serving react site

### ISSUE THREAD

**Issue by rabbah** [netlify/cli#437] opened 2019-05-07 20:01 UTC
**- Do you want to request a *feature* or report a *bug*?**
bug

**- What is the current behavior?**
```
# randomly picked react project as an example
git clone https://github.com/ahfarmer/calculator 
cd calculator
npm install
netlify dev --live
```

Expecting properly served react site and instead getting Content Encoding Error.

**- If the current behavior is a bug, please provide the steps to reproduce.**
See the attached files what shows a difference in output between curl localhost:3000 and the dev.live site.
[localhost.txt](https://github.com/netlify/netlify-dev-plugin/files/3154342/localhost.txt)
[devlive.txt](https://github.com/netlify/netlify-dev-plugin/files/3154343/devlive.txt)

**- What is the expected behavior?**
properly served html

**- Please mention your node.js, and operating system version.**
- node v11.6.0
- macos 10.14
- netlify netlify-cli/2.11.16 darwin-x64 node-v11.6.0

**Comment by erezrokah** [comment] 2021-04-25 10:19
Closing this a a duplicate of https://github.com/netlify/cli/issues/719.

See my comment [here](https://github.com/netlify/cli/issues/719#issuecomment-826297308) for more information.

**Closed by erezrokah** 2021-04-25 10:19 UTC
Labels: area: command: dev, area: dev-live, type: bug
