### ISSUE TITLE
Error: No configurator found for the git hosting service

### ISSUE THREAD

**Issue by muhammad-nauman** [netlify/cli#242] opened 2019-02-12 07:38 UTC
I'm using netlify CLI for deploying my website.
using the mentioned procedure but it is throwing this error:
 `Error: No configurator found for the git hosting service`
The repository is on the self hosted gitlab server. I have just upgraded the CLI to new version.

**Comment by bcomnes** [comment] 2019-02-12 17:39
Use the --manual flag or the web app for now.  We will be improving gitlab and bitbucket support from the CLI shortly. 

Dupe of:

- https://github.com/netlify/cli/issues/196
- https://github.com/netlify/cli/issues/195

**Closed by bcomnes** 2019-02-12 17:39 UTC
